
----------------------------------------------------------------------
-- Automatically generated by 'make_textio.pl' from l0mdt_buses_types_pkg.vhd
----------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.std_logic_textio.all;
use std.textio.all;

library l0mdt_lib;
use l0mdt_lib.mdttp_constants_pkg.all;
use l0mdt_lib.mdttp_types_pkg.all;

package mdttp_textio is


  procedure READ(L:inout LINE; VALUE:out felix_out_rt);
  procedure WRITE(L:inout LINE; VALUE:in felix_out_rt);
	
  procedure READ(L:inout LINE; VALUE:out slc_muid_rt);
  procedure WRITE(L:inout LINE; VALUE:in slc_muid_rt);
	
  procedure READ(L:inout LINE; VALUE:out slc_common_rt);
  procedure WRITE(L:inout LINE; VALUE:in slc_common_rt);
	
  procedure READ(L:inout LINE; VALUE:out slc_endcap_rt);
  procedure WRITE(L:inout LINE; VALUE:in slc_endcap_rt);
	
  procedure READ(L:inout LINE; VALUE:out slc_barrel_rt);
  procedure WRITE(L:inout LINE; VALUE:in slc_barrel_rt);
	
  procedure READ(L:inout LINE; VALUE:out slcproc_pipe_common_rt);
  procedure WRITE(L:inout LINE; VALUE:in slcproc_pipe_common_rt);
	
  procedure READ(L:inout LINE; VALUE:out slcproc_pipe_endcap_rt);
  procedure WRITE(L:inout LINE; VALUE:in slcproc_pipe_endcap_rt);
	
  procedure READ(L:inout LINE; VALUE:out slcproc_pipe_barrel_rt);
  procedure WRITE(L:inout LINE; VALUE:in slcproc_pipe_barrel_rt);
	
  procedure READ(L:inout LINE; VALUE:out tdc_rt);
  procedure WRITE(L:inout LINE; VALUE:in tdc_rt);
	
  procedure READ(L:inout LINE; VALUE:out tdcpolmux_rt);
  procedure WRITE(L:inout LINE; VALUE:in tdcpolmux_rt);
	
  procedure READ(L:inout LINE; VALUE:out slcproc_hps_sf_rt);
  procedure WRITE(L:inout LINE; VALUE:in slcproc_hps_sf_rt);
	
  procedure READ(L:inout LINE; VALUE:out tar_rt);
  procedure WRITE(L:inout LINE; VALUE:in tar_rt);
	
  procedure READ(L:inout LINE; VALUE:out hps_lsf_rt);
  procedure WRITE(L:inout LINE; VALUE:in hps_lsf_rt);
	
  procedure READ(L:inout LINE; VALUE:out hps_csf_rt);
  procedure WRITE(L:inout LINE; VALUE:in hps_csf_rt);
	
  procedure READ(L:inout LINE; VALUE:out slcpipe_ptcalc_rt);
  procedure WRITE(L:inout LINE; VALUE:in slcpipe_ptcalc_rt);
	
  procedure READ(L:inout LINE; VALUE:out sf_rt);
  procedure WRITE(L:inout LINE; VALUE:in sf_rt);
	
  procedure READ(L:inout LINE; VALUE:out ptcalc_rt);
  procedure WRITE(L:inout LINE; VALUE:in ptcalc_rt);
	
  procedure READ(L:inout LINE; VALUE:out slcpipe_mtc_endcap_rt);
  procedure WRITE(L:inout LINE; VALUE:in slcpipe_mtc_endcap_rt);
	
  procedure READ(L:inout LINE; VALUE:out slcpipe_mtc_barrel_rt);
  procedure WRITE(L:inout LINE; VALUE:in slcpipe_mtc_barrel_rt);
	
  procedure READ(L:inout LINE; VALUE:out mtc_rt);
  procedure WRITE(L:inout LINE; VALUE:in mtc_rt);
	
end mdttp_textio;

package body mdttp_textio is

  -- round up vector length to multiple of 4
  function len4r(len : integer) return integer is
  begin
    return len + (3-((len-1) mod 4));
  end len4r;


  procedure READ(L:inout LINE; VALUE:out felix_out_rt) is

    variable v_data : std_logic_vector(len4r(FELIX_OUT_DATA_LEN)-1 downto 0);
    variable v_dv : std_logic;
    variable v_header : std_logic;
    variable v_trailer : std_logic;


  begin

    HREAD(L, v_data);
    READ(L, v_dv);
    READ(L, v_header);
    READ(L, v_trailer);

    VALUE := (
        data => v_data(FELIX_OUT_DATA_LEN-1 downto 0),
        dv => v_dv,
        header => v_header,
        trailer => v_trailer);
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in felix_out_rt) is

    variable v_data : std_logic_vector(len4r(FELIX_OUT_DATA_LEN)-1 downto 0);
    variable v_dv : std_logic;
    variable v_header : std_logic;
    variable v_trailer : std_logic;

    variable v_SPACE : character;

  begin

    v_data := (others => '0');
    v_data(FELIX_OUT_DATA_LEN-1 downto 0) := VALUE.data;
    v_dv := VALUE.dv;
    v_header := VALUE.header;
    v_trailer := VALUE.trailer;
    HWRITE(L, v_data);
    WRITE(L, ' ');
    WRITE(L, v_dv);
    WRITE(L, ' ');
    WRITE(L, v_header);
    WRITE(L, ' ');
    WRITE(L, v_trailer);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out slc_muid_rt) is

    variable v_slcid : std_logic_vector(len4r(SLC_MUID_SLCID_LEN)-1 downto 0);
    variable v_slid : std_logic_vector(len4r(SLC_MUID_SLID_LEN)-1 downto 0);
    variable v_bcid : std_logic_vector(len4r(SLC_MUID_BCID_LEN)-1 downto 0);


  begin

    HREAD(L, v_slcid);
    HREAD(L, v_slid);
    HREAD(L, v_bcid);

    VALUE := (
        slcid => v_slcid(SLC_MUID_SLCID_LEN-1 downto 0),
        slid => v_slid(SLC_MUID_SLID_LEN-1 downto 0),
        bcid => v_bcid(SLC_MUID_BCID_LEN-1 downto 0));
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in slc_muid_rt) is

    variable v_slcid : std_logic_vector(len4r(SLC_MUID_SLCID_LEN)-1 downto 0);
    variable v_slid : std_logic_vector(len4r(SLC_MUID_SLID_LEN)-1 downto 0);
    variable v_bcid : std_logic_vector(len4r(SLC_MUID_BCID_LEN)-1 downto 0);

    variable v_SPACE : character;

  begin

    v_slcid := (others => '0');
    v_slcid(SLC_MUID_SLCID_LEN-1 downto 0) := VALUE.slcid;
    v_slid := (others => '0');
    v_slid(SLC_MUID_SLID_LEN-1 downto 0) := VALUE.slid;
    v_bcid := (others => '0');
    v_bcid(SLC_MUID_BCID_LEN-1 downto 0) := VALUE.bcid;
    HWRITE(L, v_slcid);
    WRITE(L, ' ');
    HWRITE(L, v_slid);
    WRITE(L, ' ');
    HWRITE(L, v_bcid);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out slc_common_rt) is

    variable v_slcid : std_logic_vector(len4r(SLC_COMMON_SLCID_LEN)-1 downto 0);
    variable v_tcsent : std_logic;
    variable v_poseta : std_logic_vector(len4r(SLC_COMMON_POSETA_LEN)-1 downto 0);
    variable v_posphi : std_logic_vector(len4r(SLC_COMMON_POSPHI_LEN)-1 downto 0);
    variable v_ptthresh : std_logic_vector(len4r(SLC_COMMON_PTTHRESH_LEN)-1 downto 0);
    variable v_charge : std_logic;


  begin

    HREAD(L, v_slcid);
    READ(L, v_tcsent);
    HREAD(L, v_poseta);
    HREAD(L, v_posphi);
    HREAD(L, v_ptthresh);
    READ(L, v_charge);

    VALUE := (
        slcid => v_slcid(SLC_COMMON_SLCID_LEN-1 downto 0),
        tcsent => v_tcsent,
        poseta => v_poseta(SLC_COMMON_POSETA_LEN-1 downto 0),
        posphi => v_posphi(SLC_COMMON_POSPHI_LEN-1 downto 0),
        ptthresh => v_ptthresh(SLC_COMMON_PTTHRESH_LEN-1 downto 0),
        charge => v_charge);
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in slc_common_rt) is

    variable v_slcid : std_logic_vector(len4r(SLC_COMMON_SLCID_LEN)-1 downto 0);
    variable v_tcsent : std_logic;
    variable v_poseta : std_logic_vector(len4r(SLC_COMMON_POSETA_LEN)-1 downto 0);
    variable v_posphi : std_logic_vector(len4r(SLC_COMMON_POSPHI_LEN)-1 downto 0);
    variable v_ptthresh : std_logic_vector(len4r(SLC_COMMON_PTTHRESH_LEN)-1 downto 0);
    variable v_charge : std_logic;

    variable v_SPACE : character;

  begin

    v_slcid := (others => '0');
    v_slcid(SLC_COMMON_SLCID_LEN-1 downto 0) := VALUE.slcid;
    v_tcsent := VALUE.tcsent;
    v_poseta := (others => '0');
    v_poseta(SLC_COMMON_POSETA_LEN-1 downto 0) := VALUE.poseta;
    v_posphi := (others => '0');
    v_posphi(SLC_COMMON_POSPHI_LEN-1 downto 0) := VALUE.posphi;
    v_ptthresh := (others => '0');
    v_ptthresh(SLC_COMMON_PTTHRESH_LEN-1 downto 0) := VALUE.ptthresh;
    v_charge := VALUE.charge;
    HWRITE(L, v_slcid);
    WRITE(L, ' ');
    WRITE(L, v_tcsent);
    WRITE(L, ' ');
    HWRITE(L, v_poseta);
    WRITE(L, ' ');
    HWRITE(L, v_posphi);
    WRITE(L, ' ');
    HWRITE(L, v_ptthresh);
    WRITE(L, ' ');
    WRITE(L, v_charge);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out slc_endcap_rt) is

    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_seg_angdtheta : std_logic_vector(len4r(SLC_ENDCAP_SEG_ANGDTHETA_LEN)-1 downto 0);
    variable v_seg_angdphi : std_logic_vector(len4r(SLC_ENDCAP_SEG_ANGDPHI_LEN)-1 downto 0);
    variable v_nswseg_poseta : std_logic_vector(len4r(SLC_ENDCAP_NSWSEG_POSETA_LEN)-1 downto 0);
    variable v_nswseg_posphi : std_logic_vector(len4r(SLC_ENDCAP_NSWSEG_POSPHI_LEN)-1 downto 0);
    variable v_nswseg_angdtheta : std_logic_vector(len4r(SLC_ENDCAP_NSWSEG_ANGDTHETA_LEN)-1 downto 0);


  begin

    READ(L, v_slc_common_r);
    HREAD(L, v_seg_angdtheta);
    HREAD(L, v_seg_angdphi);
    HREAD(L, v_nswseg_poseta);
    HREAD(L, v_nswseg_posphi);
    HREAD(L, v_nswseg_angdtheta);

    VALUE := (
        slc_common_r => v_slc_common_r,
        seg_angdtheta => v_seg_angdtheta(SLC_ENDCAP_SEG_ANGDTHETA_LEN-1 downto 0),
        seg_angdphi => v_seg_angdphi(SLC_ENDCAP_SEG_ANGDPHI_LEN-1 downto 0),
        nswseg_poseta => v_nswseg_poseta(SLC_ENDCAP_NSWSEG_POSETA_LEN-1 downto 0),
        nswseg_posphi => v_nswseg_posphi(SLC_ENDCAP_NSWSEG_POSPHI_LEN-1 downto 0),
        nswseg_angdtheta => v_nswseg_angdtheta(SLC_ENDCAP_NSWSEG_ANGDTHETA_LEN-1 downto 0));
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in slc_endcap_rt) is

    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_seg_angdtheta : std_logic_vector(len4r(SLC_ENDCAP_SEG_ANGDTHETA_LEN)-1 downto 0);
    variable v_seg_angdphi : std_logic_vector(len4r(SLC_ENDCAP_SEG_ANGDPHI_LEN)-1 downto 0);
    variable v_nswseg_poseta : std_logic_vector(len4r(SLC_ENDCAP_NSWSEG_POSETA_LEN)-1 downto 0);
    variable v_nswseg_posphi : std_logic_vector(len4r(SLC_ENDCAP_NSWSEG_POSPHI_LEN)-1 downto 0);
    variable v_nswseg_angdtheta : std_logic_vector(len4r(SLC_ENDCAP_NSWSEG_ANGDTHETA_LEN)-1 downto 0);

    variable v_SPACE : character;

  begin

    v_slc_common_r := VALUE.slc_common_r;
    v_seg_angdtheta := (others => '0');
    v_seg_angdtheta(SLC_ENDCAP_SEG_ANGDTHETA_LEN-1 downto 0) := VALUE.seg_angdtheta;
    v_seg_angdphi := (others => '0');
    v_seg_angdphi(SLC_ENDCAP_SEG_ANGDPHI_LEN-1 downto 0) := VALUE.seg_angdphi;
    v_nswseg_poseta := (others => '0');
    v_nswseg_poseta(SLC_ENDCAP_NSWSEG_POSETA_LEN-1 downto 0) := VALUE.nswseg_poseta;
    v_nswseg_posphi := (others => '0');
    v_nswseg_posphi(SLC_ENDCAP_NSWSEG_POSPHI_LEN-1 downto 0) := VALUE.nswseg_posphi;
    v_nswseg_angdtheta := (others => '0');
    v_nswseg_angdtheta(SLC_ENDCAP_NSWSEG_ANGDTHETA_LEN-1 downto 0) := VALUE.nswseg_angdtheta;
    WRITE(L, v_slc_common_r);
    WRITE(L, ' ');
    HWRITE(L, v_seg_angdtheta);
    WRITE(L, ' ');
    HWRITE(L, v_seg_angdphi);
    WRITE(L, ' ');
    HWRITE(L, v_nswseg_poseta);
    WRITE(L, ' ');
    HWRITE(L, v_nswseg_posphi);
    WRITE(L, ' ');
    HWRITE(L, v_nswseg_angdtheta);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out slc_barrel_rt) is

    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_rpc0_posz : std_logic_vector(len4r(SLC_BARREL_RPC0_POSZ_LEN)-1 downto 0);
    variable v_rpc1_posz : std_logic_vector(len4r(SLC_BARREL_RPC1_POSZ_LEN)-1 downto 0);
    variable v_rpc2_posz : std_logic_vector(len4r(SLC_BARREL_RPC2_POSZ_LEN)-1 downto 0);
    variable v_rpc3_posz : std_logic_vector(len4r(SLC_BARREL_RPC3_POSZ_LEN)-1 downto 0);
    variable v_cointype : std_logic_vector(len4r(SLC_BARREL_COINTYPE_LEN)-1 downto 0);


  begin

    READ(L, v_slc_common_r);
    HREAD(L, v_rpc0_posz);
    HREAD(L, v_rpc1_posz);
    HREAD(L, v_rpc2_posz);
    HREAD(L, v_rpc3_posz);
    HREAD(L, v_cointype);

    VALUE := (
        slc_common_r => v_slc_common_r,
        rpc0_posz => v_rpc0_posz(SLC_BARREL_RPC0_POSZ_LEN-1 downto 0),
        rpc1_posz => v_rpc1_posz(SLC_BARREL_RPC1_POSZ_LEN-1 downto 0),
        rpc2_posz => v_rpc2_posz(SLC_BARREL_RPC2_POSZ_LEN-1 downto 0),
        rpc3_posz => v_rpc3_posz(SLC_BARREL_RPC3_POSZ_LEN-1 downto 0),
        cointype => v_cointype(SLC_BARREL_COINTYPE_LEN-1 downto 0));
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in slc_barrel_rt) is

    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_rpc0_posz : std_logic_vector(len4r(SLC_BARREL_RPC0_POSZ_LEN)-1 downto 0);
    variable v_rpc1_posz : std_logic_vector(len4r(SLC_BARREL_RPC1_POSZ_LEN)-1 downto 0);
    variable v_rpc2_posz : std_logic_vector(len4r(SLC_BARREL_RPC2_POSZ_LEN)-1 downto 0);
    variable v_rpc3_posz : std_logic_vector(len4r(SLC_BARREL_RPC3_POSZ_LEN)-1 downto 0);
    variable v_cointype : std_logic_vector(len4r(SLC_BARREL_COINTYPE_LEN)-1 downto 0);

    variable v_SPACE : character;

  begin

    v_slc_common_r := VALUE.slc_common_r;
    v_rpc0_posz := (others => '0');
    v_rpc0_posz(SLC_BARREL_RPC0_POSZ_LEN-1 downto 0) := VALUE.rpc0_posz;
    v_rpc1_posz := (others => '0');
    v_rpc1_posz(SLC_BARREL_RPC1_POSZ_LEN-1 downto 0) := VALUE.rpc1_posz;
    v_rpc2_posz := (others => '0');
    v_rpc2_posz(SLC_BARREL_RPC2_POSZ_LEN-1 downto 0) := VALUE.rpc2_posz;
    v_rpc3_posz := (others => '0');
    v_rpc3_posz(SLC_BARREL_RPC3_POSZ_LEN-1 downto 0) := VALUE.rpc3_posz;
    v_cointype := (others => '0');
    v_cointype(SLC_BARREL_COINTYPE_LEN-1 downto 0) := VALUE.cointype;
    WRITE(L, v_slc_common_r);
    WRITE(L, ' ');
    HWRITE(L, v_rpc0_posz);
    WRITE(L, ' ');
    HWRITE(L, v_rpc1_posz);
    WRITE(L, ' ');
    HWRITE(L, v_rpc2_posz);
    WRITE(L, ' ');
    HWRITE(L, v_rpc3_posz);
    WRITE(L, ' ');
    HWRITE(L, v_cointype);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out slcproc_pipe_common_rt) is

    variable v_busy : std_logic;
    variable v_destsl : std_logic_vector(len4r(SLCPROC_PIPE_COMMON_DESTSL_LEN)-1 downto 0);
    variable v_phimod : std_logic_vector(len4r(SLCPROC_PIPE_COMMON_PHIMOD_LEN)-1 downto 0);
    variable v_inn_vec_mdtid : std_logic_vector(len4r(SLCPROC_PIPE_COMMON_INN_VEC_MDTID_LEN)-1 downto 0);
    variable v_mid_vec_mdtid : std_logic_vector(len4r(SLCPROC_PIPE_COMMON_MID_VEC_MDTID_LEN)-1 downto 0);
    variable v_out_vec_mdtid : std_logic_vector(len4r(SLCPROC_PIPE_COMMON_OUT_VEC_MDTID_LEN)-1 downto 0);
    variable v_ext_vec_mdtid : std_logic_vector(len4r(SLCPROC_PIPE_COMMON_EXT_VEC_MDTID_LEN)-1 downto 0);


  begin

    READ(L, v_busy);
    HREAD(L, v_destsl);
    HREAD(L, v_phimod);
    HREAD(L, v_inn_vec_mdtid);
    HREAD(L, v_mid_vec_mdtid);
    HREAD(L, v_out_vec_mdtid);
    HREAD(L, v_ext_vec_mdtid);

    VALUE := (
        busy => v_busy,
        destsl => v_destsl(SLCPROC_PIPE_COMMON_DESTSL_LEN-1 downto 0),
        phimod => v_phimod(SLCPROC_PIPE_COMMON_PHIMOD_LEN-1 downto 0),
        inn_vec_mdtid => v_inn_vec_mdtid(SLCPROC_PIPE_COMMON_INN_VEC_MDTID_LEN-1 downto 0),
        mid_vec_mdtid => v_mid_vec_mdtid(SLCPROC_PIPE_COMMON_MID_VEC_MDTID_LEN-1 downto 0),
        out_vec_mdtid => v_out_vec_mdtid(SLCPROC_PIPE_COMMON_OUT_VEC_MDTID_LEN-1 downto 0),
        ext_vec_mdtid => v_ext_vec_mdtid(SLCPROC_PIPE_COMMON_EXT_VEC_MDTID_LEN-1 downto 0));
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in slcproc_pipe_common_rt) is

    variable v_busy : std_logic;
    variable v_destsl : std_logic_vector(len4r(SLCPROC_PIPE_COMMON_DESTSL_LEN)-1 downto 0);
    variable v_phimod : std_logic_vector(len4r(SLCPROC_PIPE_COMMON_PHIMOD_LEN)-1 downto 0);
    variable v_inn_vec_mdtid : std_logic_vector(len4r(SLCPROC_PIPE_COMMON_INN_VEC_MDTID_LEN)-1 downto 0);
    variable v_mid_vec_mdtid : std_logic_vector(len4r(SLCPROC_PIPE_COMMON_MID_VEC_MDTID_LEN)-1 downto 0);
    variable v_out_vec_mdtid : std_logic_vector(len4r(SLCPROC_PIPE_COMMON_OUT_VEC_MDTID_LEN)-1 downto 0);
    variable v_ext_vec_mdtid : std_logic_vector(len4r(SLCPROC_PIPE_COMMON_EXT_VEC_MDTID_LEN)-1 downto 0);

    variable v_SPACE : character;

  begin

    v_busy := VALUE.busy;
    v_destsl := (others => '0');
    v_destsl(SLCPROC_PIPE_COMMON_DESTSL_LEN-1 downto 0) := VALUE.destsl;
    v_phimod := (others => '0');
    v_phimod(SLCPROC_PIPE_COMMON_PHIMOD_LEN-1 downto 0) := VALUE.phimod;
    v_inn_vec_mdtid := (others => '0');
    v_inn_vec_mdtid(SLCPROC_PIPE_COMMON_INN_VEC_MDTID_LEN-1 downto 0) := VALUE.inn_vec_mdtid;
    v_mid_vec_mdtid := (others => '0');
    v_mid_vec_mdtid(SLCPROC_PIPE_COMMON_MID_VEC_MDTID_LEN-1 downto 0) := VALUE.mid_vec_mdtid;
    v_out_vec_mdtid := (others => '0');
    v_out_vec_mdtid(SLCPROC_PIPE_COMMON_OUT_VEC_MDTID_LEN-1 downto 0) := VALUE.out_vec_mdtid;
    v_ext_vec_mdtid := (others => '0');
    v_ext_vec_mdtid(SLCPROC_PIPE_COMMON_EXT_VEC_MDTID_LEN-1 downto 0) := VALUE.ext_vec_mdtid;
    WRITE(L, v_busy);
    WRITE(L, ' ');
    HWRITE(L, v_destsl);
    WRITE(L, ' ');
    HWRITE(L, v_phimod);
    WRITE(L, ' ');
    HWRITE(L, v_inn_vec_mdtid);
    WRITE(L, ' ');
    HWRITE(L, v_mid_vec_mdtid);
    WRITE(L, ' ');
    HWRITE(L, v_out_vec_mdtid);
    WRITE(L, ' ');
    HWRITE(L, v_ext_vec_mdtid);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out slcproc_pipe_endcap_rt) is

    variable v_slcproc_pipe_common_r : SLCPROC_PIPE_COMMON_rt;
    variable v_slc_endcap_r : SLC_ENDCAP_rt;
    variable v_slc_muid_r : SLC_MUID_rt;


  begin

    READ(L, v_slcproc_pipe_common_r);
    READ(L, v_slc_endcap_r);
    READ(L, v_slc_muid_r);

    VALUE := (
        slcproc_pipe_common_r => v_slcproc_pipe_common_r,
        slc_endcap_r => v_slc_endcap_r,
        slc_muid_r => v_slc_muid_r);
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in slcproc_pipe_endcap_rt) is

    variable v_slcproc_pipe_common_r : SLCPROC_PIPE_COMMON_rt;
    variable v_slc_endcap_r : SLC_ENDCAP_rt;
    variable v_slc_muid_r : SLC_MUID_rt;

    variable v_SPACE : character;

  begin

    v_slcproc_pipe_common_r := VALUE.slcproc_pipe_common_r;
    v_slc_endcap_r := VALUE.slc_endcap_r;
    v_slc_muid_r := VALUE.slc_muid_r;
    WRITE(L, v_slcproc_pipe_common_r);
    WRITE(L, ' ');
    WRITE(L, v_slc_endcap_r);
    WRITE(L, ' ');
    WRITE(L, v_slc_muid_r);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out slcproc_pipe_barrel_rt) is

    variable v_slcproc_pipe_common_r : SLCPROC_PIPE_COMMON_rt;
    variable v_slc_barrel_r : SLC_BARREL_rt;
    variable v_slc_muid_r : SLC_MUID_rt;


  begin

    READ(L, v_slcproc_pipe_common_r);
    READ(L, v_slc_barrel_r);
    READ(L, v_slc_muid_r);

    VALUE := (
        slcproc_pipe_common_r => v_slcproc_pipe_common_r,
        slc_barrel_r => v_slc_barrel_r,
        slc_muid_r => v_slc_muid_r);
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in slcproc_pipe_barrel_rt) is

    variable v_slcproc_pipe_common_r : SLCPROC_PIPE_COMMON_rt;
    variable v_slc_barrel_r : SLC_BARREL_rt;
    variable v_slc_muid_r : SLC_MUID_rt;

    variable v_SPACE : character;

  begin

    v_slcproc_pipe_common_r := VALUE.slcproc_pipe_common_r;
    v_slc_barrel_r := VALUE.slc_barrel_r;
    v_slc_muid_r := VALUE.slc_muid_r;
    WRITE(L, v_slcproc_pipe_common_r);
    WRITE(L, ' ');
    WRITE(L, v_slc_barrel_r);
    WRITE(L, ' ');
    WRITE(L, v_slc_muid_r);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out tdc_rt) is

    variable v_chanid : std_logic_vector(len4r(TDC_CHANID_LEN)-1 downto 0);
    variable v_edgemode : std_logic_vector(len4r(TDC_EDGEMODE_LEN)-1 downto 0);
    variable v_coarsetime : std_logic_vector(len4r(TDC_COARSETIME_LEN)-1 downto 0);
    variable v_finetime : std_logic_vector(len4r(TDC_FINETIME_LEN)-1 downto 0);
    variable v_pulsewidth : std_logic_vector(len4r(TDC_PULSEWIDTH_LEN)-1 downto 0);


  begin

    HREAD(L, v_chanid);
    HREAD(L, v_edgemode);
    HREAD(L, v_coarsetime);
    HREAD(L, v_finetime);
    HREAD(L, v_pulsewidth);

    VALUE := (
        chanid => v_chanid(TDC_CHANID_LEN-1 downto 0),
        edgemode => v_edgemode(TDC_EDGEMODE_LEN-1 downto 0),
        coarsetime => v_coarsetime(TDC_COARSETIME_LEN-1 downto 0),
        finetime => v_finetime(TDC_FINETIME_LEN-1 downto 0),
        pulsewidth => v_pulsewidth(TDC_PULSEWIDTH_LEN-1 downto 0));
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in tdc_rt) is

    variable v_chanid : std_logic_vector(len4r(TDC_CHANID_LEN)-1 downto 0);
    variable v_edgemode : std_logic_vector(len4r(TDC_EDGEMODE_LEN)-1 downto 0);
    variable v_coarsetime : std_logic_vector(len4r(TDC_COARSETIME_LEN)-1 downto 0);
    variable v_finetime : std_logic_vector(len4r(TDC_FINETIME_LEN)-1 downto 0);
    variable v_pulsewidth : std_logic_vector(len4r(TDC_PULSEWIDTH_LEN)-1 downto 0);

    variable v_SPACE : character;

  begin

    v_chanid := (others => '0');
    v_chanid(TDC_CHANID_LEN-1 downto 0) := VALUE.chanid;
    v_edgemode := (others => '0');
    v_edgemode(TDC_EDGEMODE_LEN-1 downto 0) := VALUE.edgemode;
    v_coarsetime := (others => '0');
    v_coarsetime(TDC_COARSETIME_LEN-1 downto 0) := VALUE.coarsetime;
    v_finetime := (others => '0');
    v_finetime(TDC_FINETIME_LEN-1 downto 0) := VALUE.finetime;
    v_pulsewidth := (others => '0');
    v_pulsewidth(TDC_PULSEWIDTH_LEN-1 downto 0) := VALUE.pulsewidth;
    HWRITE(L, v_chanid);
    WRITE(L, ' ');
    HWRITE(L, v_edgemode);
    WRITE(L, ' ');
    HWRITE(L, v_coarsetime);
    WRITE(L, ' ');
    HWRITE(L, v_finetime);
    WRITE(L, ' ');
    HWRITE(L, v_pulsewidth);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out tdcpolmux_rt) is

    variable v_tdc_r : TDC_rt;
    variable v_fiberid : std_logic_vector(len4r(TDCPOLMUX_FIBERID_LEN)-1 downto 0);
    variable v_elinkid : std_logic_vector(len4r(TDCPOLMUX_ELINKID_LEN)-1 downto 0);
    variable v_datavalid : std_logic;


  begin

    READ(L, v_tdc_r);
    HREAD(L, v_fiberid);
    HREAD(L, v_elinkid);
    READ(L, v_datavalid);

    VALUE := (
        tdc_r => v_tdc_r,
        fiberid => v_fiberid(TDCPOLMUX_FIBERID_LEN-1 downto 0),
        elinkid => v_elinkid(TDCPOLMUX_ELINKID_LEN-1 downto 0),
        datavalid => v_datavalid);
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in tdcpolmux_rt) is

    variable v_tdc_r : TDC_rt;
    variable v_fiberid : std_logic_vector(len4r(TDCPOLMUX_FIBERID_LEN)-1 downto 0);
    variable v_elinkid : std_logic_vector(len4r(TDCPOLMUX_ELINKID_LEN)-1 downto 0);
    variable v_datavalid : std_logic;

    variable v_SPACE : character;

  begin

    v_tdc_r := VALUE.tdc_r;
    v_fiberid := (others => '0');
    v_fiberid(TDCPOLMUX_FIBERID_LEN-1 downto 0) := VALUE.fiberid;
    v_elinkid := (others => '0');
    v_elinkid(TDCPOLMUX_ELINKID_LEN-1 downto 0) := VALUE.elinkid;
    v_datavalid := VALUE.datavalid;
    WRITE(L, v_tdc_r);
    WRITE(L, ' ');
    HWRITE(L, v_fiberid);
    WRITE(L, ' ');
    HWRITE(L, v_elinkid);
    WRITE(L, ' ');
    WRITE(L, v_datavalid);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out slcproc_hps_sf_rt) is

    variable v_slc_valid : std_logic;
    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_mdtseg_dest : std_logic_vector(len4r(SLCPROC_HPS_SF_MDTSEG_DEST_LEN)-1 downto 0);
    variable v_vec_mdtid : std_logic_vector(len4r(SLCPROC_HPS_SF_VEC_MDTID_LEN)-1 downto 0);
    variable v_vec_pos : std_logic_vector(len4r(SLCPROC_HPS_SF_VEC_POS_LEN)-1 downto 0);
    variable v_vec_ang : std_logic_vector(len4r(SLCPROC_HPS_SF_VEC_ANG_LEN)-1 downto 0);


  begin

    READ(L, v_slc_valid);
    READ(L, v_slc_muid_r);
    HREAD(L, v_mdtseg_dest);
    HREAD(L, v_vec_mdtid);
    HREAD(L, v_vec_pos);
    HREAD(L, v_vec_ang);

    VALUE := (
        slc_valid => v_slc_valid,
        slc_muid_r => v_slc_muid_r,
        mdtseg_dest => v_mdtseg_dest(SLCPROC_HPS_SF_MDTSEG_DEST_LEN-1 downto 0),
        vec_mdtid => v_vec_mdtid(SLCPROC_HPS_SF_VEC_MDTID_LEN-1 downto 0),
        vec_pos => v_vec_pos(SLCPROC_HPS_SF_VEC_POS_LEN-1 downto 0),
        vec_ang => v_vec_ang(SLCPROC_HPS_SF_VEC_ANG_LEN-1 downto 0));
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in slcproc_hps_sf_rt) is

    variable v_slc_valid : std_logic;
    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_mdtseg_dest : std_logic_vector(len4r(SLCPROC_HPS_SF_MDTSEG_DEST_LEN)-1 downto 0);
    variable v_vec_mdtid : std_logic_vector(len4r(SLCPROC_HPS_SF_VEC_MDTID_LEN)-1 downto 0);
    variable v_vec_pos : std_logic_vector(len4r(SLCPROC_HPS_SF_VEC_POS_LEN)-1 downto 0);
    variable v_vec_ang : std_logic_vector(len4r(SLCPROC_HPS_SF_VEC_ANG_LEN)-1 downto 0);

    variable v_SPACE : character;

  begin

    v_slc_valid := VALUE.slc_valid;
    v_slc_muid_r := VALUE.slc_muid_r;
    v_mdtseg_dest := (others => '0');
    v_mdtseg_dest(SLCPROC_HPS_SF_MDTSEG_DEST_LEN-1 downto 0) := VALUE.mdtseg_dest;
    v_vec_mdtid := (others => '0');
    v_vec_mdtid(SLCPROC_HPS_SF_VEC_MDTID_LEN-1 downto 0) := VALUE.vec_mdtid;
    v_vec_pos := (others => '0');
    v_vec_pos(SLCPROC_HPS_SF_VEC_POS_LEN-1 downto 0) := VALUE.vec_pos;
    v_vec_ang := (others => '0');
    v_vec_ang(SLCPROC_HPS_SF_VEC_ANG_LEN-1 downto 0) := VALUE.vec_ang;
    WRITE(L, v_slc_valid);
    WRITE(L, ' ');
    WRITE(L, v_slc_muid_r);
    WRITE(L, ' ');
    HWRITE(L, v_mdtseg_dest);
    WRITE(L, ' ');
    HWRITE(L, v_vec_mdtid);
    WRITE(L, ' ');
    HWRITE(L, v_vec_pos);
    WRITE(L, ' ');
    HWRITE(L, v_vec_ang);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out tar_rt) is

    variable v_mdt_tube_layer : std_logic_vector(len4r(TAR_MDT_TUBE_LAYER_LEN)-1 downto 0);
    variable v_mdt_tube_num : std_logic_vector(len4r(TAR_MDT_TUBE_NUM_LEN)-1 downto 0);
    variable v_mdt_tube_rho : std_logic_vector(len4r(TAR_MDT_TUBE_RHO_LEN)-1 downto 0);
    variable v_mdt_tube_z : std_logic_vector(len4r(TAR_MDT_TUBE_Z_LEN)-1 downto 0);
    variable v_mdt_tube_time : std_logic_vector(len4r(TAR_MDT_TUBE_TIME_LEN)-1 downto 0);


  begin

    HREAD(L, v_mdt_tube_layer);
    HREAD(L, v_mdt_tube_num);
    HREAD(L, v_mdt_tube_rho);
    HREAD(L, v_mdt_tube_z);
    HREAD(L, v_mdt_tube_time);

    VALUE := (
        mdt_tube_layer => v_mdt_tube_layer(TAR_MDT_TUBE_LAYER_LEN-1 downto 0),
        mdt_tube_num => v_mdt_tube_num(TAR_MDT_TUBE_NUM_LEN-1 downto 0),
        mdt_tube_rho => v_mdt_tube_rho(TAR_MDT_TUBE_RHO_LEN-1 downto 0),
        mdt_tube_z => v_mdt_tube_z(TAR_MDT_TUBE_Z_LEN-1 downto 0),
        mdt_tube_time => v_mdt_tube_time(TAR_MDT_TUBE_TIME_LEN-1 downto 0));
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in tar_rt) is

    variable v_mdt_tube_layer : std_logic_vector(len4r(TAR_MDT_TUBE_LAYER_LEN)-1 downto 0);
    variable v_mdt_tube_num : std_logic_vector(len4r(TAR_MDT_TUBE_NUM_LEN)-1 downto 0);
    variable v_mdt_tube_rho : std_logic_vector(len4r(TAR_MDT_TUBE_RHO_LEN)-1 downto 0);
    variable v_mdt_tube_z : std_logic_vector(len4r(TAR_MDT_TUBE_Z_LEN)-1 downto 0);
    variable v_mdt_tube_time : std_logic_vector(len4r(TAR_MDT_TUBE_TIME_LEN)-1 downto 0);

    variable v_SPACE : character;

  begin

    v_mdt_tube_layer := (others => '0');
    v_mdt_tube_layer(TAR_MDT_TUBE_LAYER_LEN-1 downto 0) := VALUE.mdt_tube_layer;
    v_mdt_tube_num := (others => '0');
    v_mdt_tube_num(TAR_MDT_TUBE_NUM_LEN-1 downto 0) := VALUE.mdt_tube_num;
    v_mdt_tube_rho := (others => '0');
    v_mdt_tube_rho(TAR_MDT_TUBE_RHO_LEN-1 downto 0) := VALUE.mdt_tube_rho;
    v_mdt_tube_z := (others => '0');
    v_mdt_tube_z(TAR_MDT_TUBE_Z_LEN-1 downto 0) := VALUE.mdt_tube_z;
    v_mdt_tube_time := (others => '0');
    v_mdt_tube_time(TAR_MDT_TUBE_TIME_LEN-1 downto 0) := VALUE.mdt_tube_time;
    HWRITE(L, v_mdt_tube_layer);
    WRITE(L, ' ');
    HWRITE(L, v_mdt_tube_num);
    WRITE(L, ' ');
    HWRITE(L, v_mdt_tube_rho);
    WRITE(L, ' ');
    HWRITE(L, v_mdt_tube_z);
    WRITE(L, ' ');
    HWRITE(L, v_mdt_tube_time);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out hps_lsf_rt) is

    variable v_data_valid : std_logic;
    variable v_mdt_localx : std_logic_vector(len4r(HPS_LSF_MDT_LOCALX_LEN)-1 downto 0);
    variable v_mdt_localy : std_logic_vector(len4r(HPS_LSF_MDT_LOCALY_LEN)-1 downto 0);
    variable v_mdt_radius : std_logic_vector(len4r(HPS_LSF_MDT_RADIUS_LEN)-1 downto 0);


  begin

    READ(L, v_data_valid);
    HREAD(L, v_mdt_localx);
    HREAD(L, v_mdt_localy);
    HREAD(L, v_mdt_radius);

    VALUE := (
        data_valid => v_data_valid,
        mdt_localx => v_mdt_localx(HPS_LSF_MDT_LOCALX_LEN-1 downto 0),
        mdt_localy => v_mdt_localy(HPS_LSF_MDT_LOCALY_LEN-1 downto 0),
        mdt_radius => v_mdt_radius(HPS_LSF_MDT_RADIUS_LEN-1 downto 0));
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in hps_lsf_rt) is

    variable v_data_valid : std_logic;
    variable v_mdt_localx : std_logic_vector(len4r(HPS_LSF_MDT_LOCALX_LEN)-1 downto 0);
    variable v_mdt_localy : std_logic_vector(len4r(HPS_LSF_MDT_LOCALY_LEN)-1 downto 0);
    variable v_mdt_radius : std_logic_vector(len4r(HPS_LSF_MDT_RADIUS_LEN)-1 downto 0);

    variable v_SPACE : character;

  begin

    v_data_valid := VALUE.data_valid;
    v_mdt_localx := (others => '0');
    v_mdt_localx(HPS_LSF_MDT_LOCALX_LEN-1 downto 0) := VALUE.mdt_localx;
    v_mdt_localy := (others => '0');
    v_mdt_localy(HPS_LSF_MDT_LOCALY_LEN-1 downto 0) := VALUE.mdt_localy;
    v_mdt_radius := (others => '0');
    v_mdt_radius(HPS_LSF_MDT_RADIUS_LEN-1 downto 0) := VALUE.mdt_radius;
    WRITE(L, v_data_valid);
    WRITE(L, ' ');
    HWRITE(L, v_mdt_localx);
    WRITE(L, ' ');
    HWRITE(L, v_mdt_localy);
    WRITE(L, ' ');
    HWRITE(L, v_mdt_radius);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out hps_csf_rt) is

    variable v_data_valid : std_logic;
    variable v_mdt_localx : std_logic_vector(len4r(HPS_CSF_MDT_LOCALX_LEN)-1 downto 0);
    variable v_mdt_localy : std_logic_vector(len4r(HPS_CSF_MDT_LOCALY_LEN)-1 downto 0);
    variable v_mdt_radius : std_logic_vector(len4r(HPS_CSF_MDT_RADIUS_LEN)-1 downto 0);


  begin

    READ(L, v_data_valid);
    HREAD(L, v_mdt_localx);
    HREAD(L, v_mdt_localy);
    HREAD(L, v_mdt_radius);

    VALUE := (
        data_valid => v_data_valid,
        mdt_localx => v_mdt_localx(HPS_CSF_MDT_LOCALX_LEN-1 downto 0),
        mdt_localy => v_mdt_localy(HPS_CSF_MDT_LOCALY_LEN-1 downto 0),
        mdt_radius => v_mdt_radius(HPS_CSF_MDT_RADIUS_LEN-1 downto 0));
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in hps_csf_rt) is

    variable v_data_valid : std_logic;
    variable v_mdt_localx : std_logic_vector(len4r(HPS_CSF_MDT_LOCALX_LEN)-1 downto 0);
    variable v_mdt_localy : std_logic_vector(len4r(HPS_CSF_MDT_LOCALY_LEN)-1 downto 0);
    variable v_mdt_radius : std_logic_vector(len4r(HPS_CSF_MDT_RADIUS_LEN)-1 downto 0);

    variable v_SPACE : character;

  begin

    v_data_valid := VALUE.data_valid;
    v_mdt_localx := (others => '0');
    v_mdt_localx(HPS_CSF_MDT_LOCALX_LEN-1 downto 0) := VALUE.mdt_localx;
    v_mdt_localy := (others => '0');
    v_mdt_localy(HPS_CSF_MDT_LOCALY_LEN-1 downto 0) := VALUE.mdt_localy;
    v_mdt_radius := (others => '0');
    v_mdt_radius(HPS_CSF_MDT_RADIUS_LEN-1 downto 0) := VALUE.mdt_radius;
    WRITE(L, v_data_valid);
    WRITE(L, ' ');
    HWRITE(L, v_mdt_localx);
    WRITE(L, ' ');
    HWRITE(L, v_mdt_localy);
    WRITE(L, ' ');
    HWRITE(L, v_mdt_radius);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out slcpipe_ptcalc_rt) is

    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_phimod : std_logic_vector(len4r(SLCPIPE_PTCALC_PHIMOD_LEN)-1 downto 0);
    variable v_charge : std_logic;


  begin

    READ(L, v_slc_muid_r);
    HREAD(L, v_phimod);
    READ(L, v_charge);

    VALUE := (
        slc_muid_r => v_slc_muid_r,
        phimod => v_phimod(SLCPIPE_PTCALC_PHIMOD_LEN-1 downto 0),
        charge => v_charge);
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in slcpipe_ptcalc_rt) is

    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_phimod : std_logic_vector(len4r(SLCPIPE_PTCALC_PHIMOD_LEN)-1 downto 0);
    variable v_charge : std_logic;

    variable v_SPACE : character;

  begin

    v_slc_muid_r := VALUE.slc_muid_r;
    v_phimod := (others => '0');
    v_phimod(SLCPIPE_PTCALC_PHIMOD_LEN-1 downto 0) := VALUE.phimod;
    v_charge := VALUE.charge;
    WRITE(L, v_slc_muid_r);
    WRITE(L, ' ');
    HWRITE(L, v_phimod);
    WRITE(L, ' ');
    WRITE(L, v_charge);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out sf_rt) is

    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_vec_mdtid : std_logic_vector(len4r(SF_VEC_MDTID_LEN)-1 downto 0);
    variable v_segvalid : std_logic;
    variable v_segpos : std_logic_vector(len4r(SF_SEGPOS_LEN)-1 downto 0);
    variable v_segangle : std_logic_vector(len4r(SF_SEGANGLE_LEN)-1 downto 0);
    variable v_segquality : std_logic;


  begin

    READ(L, v_slc_muid_r);
    HREAD(L, v_vec_mdtid);
    READ(L, v_segvalid);
    HREAD(L, v_segpos);
    HREAD(L, v_segangle);
    READ(L, v_segquality);

    VALUE := (
        slc_muid_r => v_slc_muid_r,
        vec_mdtid => v_vec_mdtid(SF_VEC_MDTID_LEN-1 downto 0),
        segvalid => v_segvalid,
        segpos => v_segpos(SF_SEGPOS_LEN-1 downto 0),
        segangle => v_segangle(SF_SEGANGLE_LEN-1 downto 0),
        segquality => v_segquality);
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in sf_rt) is

    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_vec_mdtid : std_logic_vector(len4r(SF_VEC_MDTID_LEN)-1 downto 0);
    variable v_segvalid : std_logic;
    variable v_segpos : std_logic_vector(len4r(SF_SEGPOS_LEN)-1 downto 0);
    variable v_segangle : std_logic_vector(len4r(SF_SEGANGLE_LEN)-1 downto 0);
    variable v_segquality : std_logic;

    variable v_SPACE : character;

  begin

    v_slc_muid_r := VALUE.slc_muid_r;
    v_vec_mdtid := (others => '0');
    v_vec_mdtid(SF_VEC_MDTID_LEN-1 downto 0) := VALUE.vec_mdtid;
    v_segvalid := VALUE.segvalid;
    v_segpos := (others => '0');
    v_segpos(SF_SEGPOS_LEN-1 downto 0) := VALUE.segpos;
    v_segangle := (others => '0');
    v_segangle(SF_SEGANGLE_LEN-1 downto 0) := VALUE.segangle;
    v_segquality := VALUE.segquality;
    WRITE(L, v_slc_muid_r);
    WRITE(L, ' ');
    HWRITE(L, v_vec_mdtid);
    WRITE(L, ' ');
    WRITE(L, v_segvalid);
    WRITE(L, ' ');
    HWRITE(L, v_segpos);
    WRITE(L, ' ');
    HWRITE(L, v_segangle);
    WRITE(L, ' ');
    WRITE(L, v_segquality);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out ptcalc_rt) is

    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_eta : std_logic_vector(len4r(PTCALC_ETA_LEN)-1 downto 0);
    variable v_pt : std_logic_vector(len4r(PTCALC_PT_LEN)-1 downto 0);
    variable v_ptthresh : std_logic_vector(len4r(PTCALC_PTTHRESH_LEN)-1 downto 0);
    variable v_charge : std_logic;
    variable v_nsegments : std_logic_vector(len4r(PTCALC_NSEGMENTS_LEN)-1 downto 0);
    variable v_quality : std_logic_vector(len4r(PTCALC_QUALITY_LEN)-1 downto 0);


  begin

    READ(L, v_slc_muid_r);
    HREAD(L, v_eta);
    HREAD(L, v_pt);
    HREAD(L, v_ptthresh);
    READ(L, v_charge);
    HREAD(L, v_nsegments);
    HREAD(L, v_quality);

    VALUE := (
        slc_muid_r => v_slc_muid_r,
        eta => v_eta(PTCALC_ETA_LEN-1 downto 0),
        pt => v_pt(PTCALC_PT_LEN-1 downto 0),
        ptthresh => v_ptthresh(PTCALC_PTTHRESH_LEN-1 downto 0),
        charge => v_charge,
        nsegments => v_nsegments(PTCALC_NSEGMENTS_LEN-1 downto 0),
        quality => v_quality(PTCALC_QUALITY_LEN-1 downto 0));
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in ptcalc_rt) is

    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_eta : std_logic_vector(len4r(PTCALC_ETA_LEN)-1 downto 0);
    variable v_pt : std_logic_vector(len4r(PTCALC_PT_LEN)-1 downto 0);
    variable v_ptthresh : std_logic_vector(len4r(PTCALC_PTTHRESH_LEN)-1 downto 0);
    variable v_charge : std_logic;
    variable v_nsegments : std_logic_vector(len4r(PTCALC_NSEGMENTS_LEN)-1 downto 0);
    variable v_quality : std_logic_vector(len4r(PTCALC_QUALITY_LEN)-1 downto 0);

    variable v_SPACE : character;

  begin

    v_slc_muid_r := VALUE.slc_muid_r;
    v_eta := (others => '0');
    v_eta(PTCALC_ETA_LEN-1 downto 0) := VALUE.eta;
    v_pt := (others => '0');
    v_pt(PTCALC_PT_LEN-1 downto 0) := VALUE.pt;
    v_ptthresh := (others => '0');
    v_ptthresh(PTCALC_PTTHRESH_LEN-1 downto 0) := VALUE.ptthresh;
    v_charge := VALUE.charge;
    v_nsegments := (others => '0');
    v_nsegments(PTCALC_NSEGMENTS_LEN-1 downto 0) := VALUE.nsegments;
    v_quality := (others => '0');
    v_quality(PTCALC_QUALITY_LEN-1 downto 0) := VALUE.quality;
    WRITE(L, v_slc_muid_r);
    WRITE(L, ' ');
    HWRITE(L, v_eta);
    WRITE(L, ' ');
    HWRITE(L, v_pt);
    WRITE(L, ' ');
    HWRITE(L, v_ptthresh);
    WRITE(L, ' ');
    WRITE(L, v_charge);
    WRITE(L, ' ');
    HWRITE(L, v_nsegments);
    WRITE(L, ' ');
    HWRITE(L, v_quality);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out slcpipe_mtc_endcap_rt) is

    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_busy : std_logic;
    variable v_destsl : std_logic_vector(len4r(SLCPIPE_MTC_ENDCAP_DESTSL_LEN)-1 downto 0);


  begin

    READ(L, v_slc_muid_r);
    READ(L, v_slc_common_r);
    READ(L, v_busy);
    HREAD(L, v_destsl);

    VALUE := (
        slc_muid_r => v_slc_muid_r,
        slc_common_r => v_slc_common_r,
        busy => v_busy,
        destsl => v_destsl(SLCPIPE_MTC_ENDCAP_DESTSL_LEN-1 downto 0));
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in slcpipe_mtc_endcap_rt) is

    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_busy : std_logic;
    variable v_destsl : std_logic_vector(len4r(SLCPIPE_MTC_ENDCAP_DESTSL_LEN)-1 downto 0);

    variable v_SPACE : character;

  begin

    v_slc_muid_r := VALUE.slc_muid_r;
    v_slc_common_r := VALUE.slc_common_r;
    v_busy := VALUE.busy;
    v_destsl := (others => '0');
    v_destsl(SLCPIPE_MTC_ENDCAP_DESTSL_LEN-1 downto 0) := VALUE.destsl;
    WRITE(L, v_slc_muid_r);
    WRITE(L, ' ');
    WRITE(L, v_slc_common_r);
    WRITE(L, ' ');
    WRITE(L, v_busy);
    WRITE(L, ' ');
    HWRITE(L, v_destsl);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out slcpipe_mtc_barrel_rt) is

    variable v_cointype : std_logic_vector(len4r(SLCPIPE_MTC_BARREL_COINTYPE_LEN)-1 downto 0);
    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_busy : std_logic;
    variable v_destsl : std_logic_vector(len4r(SLCPIPE_MTC_BARREL_DESTSL_LEN)-1 downto 0);


  begin

    HREAD(L, v_cointype);
    READ(L, v_slc_muid_r);
    READ(L, v_slc_common_r);
    READ(L, v_busy);
    HREAD(L, v_destsl);

    VALUE := (
        cointype => v_cointype(SLCPIPE_MTC_BARREL_COINTYPE_LEN-1 downto 0),
        slc_muid_r => v_slc_muid_r,
        slc_common_r => v_slc_common_r,
        busy => v_busy,
        destsl => v_destsl(SLCPIPE_MTC_BARREL_DESTSL_LEN-1 downto 0));
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in slcpipe_mtc_barrel_rt) is

    variable v_cointype : std_logic_vector(len4r(SLCPIPE_MTC_BARREL_COINTYPE_LEN)-1 downto 0);
    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_busy : std_logic;
    variable v_destsl : std_logic_vector(len4r(SLCPIPE_MTC_BARREL_DESTSL_LEN)-1 downto 0);

    variable v_SPACE : character;

  begin

    v_cointype := (others => '0');
    v_cointype(SLCPIPE_MTC_BARREL_COINTYPE_LEN-1 downto 0) := VALUE.cointype;
    v_slc_muid_r := VALUE.slc_muid_r;
    v_slc_common_r := VALUE.slc_common_r;
    v_busy := VALUE.busy;
    v_destsl := (others => '0');
    v_destsl(SLCPIPE_MTC_BARREL_DESTSL_LEN-1 downto 0) := VALUE.destsl;
    HWRITE(L, v_cointype);
    WRITE(L, ' ');
    WRITE(L, v_slc_muid_r);
    WRITE(L, ' ');
    WRITE(L, v_slc_common_r);
    WRITE(L, ' ');
    WRITE(L, v_busy);
    WRITE(L, ' ');
    HWRITE(L, v_destsl);
  end WRITE;


  procedure READ(L:inout LINE; VALUE:out mtc_rt) is

    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_eta : std_logic_vector(len4r(MTC_ETA_LEN)-1 downto 0);
    variable v_pt : std_logic_vector(len4r(MTC_PT_LEN)-1 downto 0);
    variable v_ptthresh : std_logic_vector(len4r(MTC_PTTHRESH_LEN)-1 downto 0);
    variable v_charge : std_logic;
    variable v_procflags : std_logic_vector(len4r(MTC_PROCFLAGS_LEN)-1 downto 0);
    variable v_nsegments : std_logic_vector(len4r(MTC_NSEGMENTS_LEN)-1 downto 0);
    variable v_quality : std_logic_vector(len4r(MTC_QUALITY_LEN)-1 downto 0);


  begin

    READ(L, v_slc_common_r);
    HREAD(L, v_eta);
    HREAD(L, v_pt);
    HREAD(L, v_ptthresh);
    READ(L, v_charge);
    HREAD(L, v_procflags);
    HREAD(L, v_nsegments);
    HREAD(L, v_quality);

    VALUE := (
        slc_common_r => v_slc_common_r,
        eta => v_eta(MTC_ETA_LEN-1 downto 0),
        pt => v_pt(MTC_PT_LEN-1 downto 0),
        ptthresh => v_ptthresh(MTC_PTTHRESH_LEN-1 downto 0),
        charge => v_charge,
        procflags => v_procflags(MTC_PROCFLAGS_LEN-1 downto 0),
        nsegments => v_nsegments(MTC_NSEGMENTS_LEN-1 downto 0),
        quality => v_quality(MTC_QUALITY_LEN-1 downto 0));
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in mtc_rt) is

    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_eta : std_logic_vector(len4r(MTC_ETA_LEN)-1 downto 0);
    variable v_pt : std_logic_vector(len4r(MTC_PT_LEN)-1 downto 0);
    variable v_ptthresh : std_logic_vector(len4r(MTC_PTTHRESH_LEN)-1 downto 0);
    variable v_charge : std_logic;
    variable v_procflags : std_logic_vector(len4r(MTC_PROCFLAGS_LEN)-1 downto 0);
    variable v_nsegments : std_logic_vector(len4r(MTC_NSEGMENTS_LEN)-1 downto 0);
    variable v_quality : std_logic_vector(len4r(MTC_QUALITY_LEN)-1 downto 0);

    variable v_SPACE : character;

  begin

    v_slc_common_r := VALUE.slc_common_r;
    v_eta := (others => '0');
    v_eta(MTC_ETA_LEN-1 downto 0) := VALUE.eta;
    v_pt := (others => '0');
    v_pt(MTC_PT_LEN-1 downto 0) := VALUE.pt;
    v_ptthresh := (others => '0');
    v_ptthresh(MTC_PTTHRESH_LEN-1 downto 0) := VALUE.ptthresh;
    v_charge := VALUE.charge;
    v_procflags := (others => '0');
    v_procflags(MTC_PROCFLAGS_LEN-1 downto 0) := VALUE.procflags;
    v_nsegments := (others => '0');
    v_nsegments(MTC_NSEGMENTS_LEN-1 downto 0) := VALUE.nsegments;
    v_quality := (others => '0');
    v_quality(MTC_QUALITY_LEN-1 downto 0) := VALUE.quality;
    WRITE(L, v_slc_common_r);
    WRITE(L, ' ');
    HWRITE(L, v_eta);
    WRITE(L, ' ');
    HWRITE(L, v_pt);
    WRITE(L, ' ');
    HWRITE(L, v_ptthresh);
    WRITE(L, ' ');
    WRITE(L, v_charge);
    WRITE(L, ' ');
    HWRITE(L, v_procflags);
    WRITE(L, ' ');
    HWRITE(L, v_nsegments);
    WRITE(L, ' ');
    HWRITE(L, v_quality);
  end WRITE;

end mdttp_textio;
