
----------------------------------------------------------------------
-- Automatically generated by 'make_textio.pl' from l0mdt_buses_types_pkg.vhd
----------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.std_logic_textio.all;
use std.textio.all;

library l0mdt_lib;
use l0mdt_lib.mdttp_constants_pkg.all;
use l0mdt_lib.mdttp_types_pkg.all;

package mdttp_textio is


  procedure READ(L  : inout line; VALUE : out felix_out_rt);
  procedure WRITE(L : inout line; VALUE : in felix_out_rt);

  procedure READ(L  : inout line; VALUE : out slc_muid_rt);
  procedure WRITE(L : inout line; VALUE : in slc_muid_rt);

  procedure READ(L  : inout line; VALUE : out slc_common_rt);
  procedure WRITE(L : inout line; VALUE : in slc_common_rt);

  procedure READ(L  : inout line; VALUE : out slc_endcap_rt);
  procedure WRITE(L : inout line; VALUE : in slc_endcap_rt);

  procedure READ(L  : inout line; VALUE : out slc_barrel_rt);
  procedure WRITE(L : inout line; VALUE : in slc_barrel_rt);

  procedure READ(L  : inout line; VALUE : out slcproc_pipe_common_rt);
  procedure WRITE(L : inout line; VALUE : in slcproc_pipe_common_rt);

  procedure READ(L  : inout line; VALUE : out slcproc_pipe_endcap_rt);
  procedure WRITE(L : inout line; VALUE : in slcproc_pipe_endcap_rt);

  procedure READ(L  : inout line; VALUE : out slcproc_pipe_barrel_rt);
  procedure WRITE(L : inout line; VALUE : in slcproc_pipe_barrel_rt);

  procedure READ(L  : inout line; VALUE : out tdc_rt);
  procedure WRITE(L : inout line; VALUE : in tdc_rt);

  procedure READ(L  : inout line; VALUE : out tdcpolmux_rt);
  procedure WRITE(L : inout line; VALUE : in tdcpolmux_rt);

  procedure READ(L  : inout line; VALUE : out slcproc_hps_sf_rt);
  procedure WRITE(L : inout line; VALUE : in slcproc_hps_sf_rt);

  procedure READ(L  : inout line; VALUE : out tar_rt);
  procedure WRITE(L : inout line; VALUE : in tar_rt);

  procedure READ(L  : inout line; VALUE : out hps_lsf_rt);
  procedure WRITE(L : inout line; VALUE : in hps_lsf_rt);

  procedure READ(L  : inout line; VALUE : out hps_csf_rt);
  procedure WRITE(L : inout line; VALUE : in hps_csf_rt);

  procedure READ(L  : inout line; VALUE : out slcpipe_ptcalc_rt);
  procedure WRITE(L : inout line; VALUE : in slcpipe_ptcalc_rt);

  procedure READ(L  : inout line; VALUE : out sf_rt);
  procedure WRITE(L : inout line; VALUE : in sf_rt);

  procedure READ(L  : inout line; VALUE : out ptcalc_rt);
  procedure WRITE(L : inout line; VALUE : in ptcalc_rt);

  procedure READ(L  : inout line; VALUE : out slcpipe_mtc_endcap_rt);
  procedure WRITE(L : inout line; VALUE : in slcpipe_mtc_endcap_rt);

  procedure READ(L  : inout line; VALUE : out slcpipe_mtc_barrel_rt);
  procedure WRITE(L : inout line; VALUE : in slcpipe_mtc_barrel_rt);

  procedure READ(L  : inout line; VALUE : out mtc_rt);
  procedure WRITE(L : inout line; VALUE : in mtc_rt);

end mdttp_textio;

package body mdttp_textio is


  -- round up vector length to multiple of 4
  function len4r(len : integer) return integer is
  begin
    return len + (3-((len-1) mod 4));
  end len4r;

  procedure READ(L : inout line; VALUE : out felix_out_rt) is
    variable i_dv      : integer;
    variable i_header  : integer;
    variable i_trailer : integer;

    variable v_data    : std_logic_vector(FELIX_OUT_DATA_LEN-1 downto 0);
    variable v_dv      : std_logic;
    variable v_header  : std_logic;
    variable v_trailer : std_logic;

    variable v_SPACE : character;

  begin

    HREAD(L, v_data);
    READ(L, v_SPACE);
    READ(L, i_dv);
    READ(L, v_SPACE);
    READ(L, i_header);
    READ(L, v_SPACE);
    READ(L, i_trailer);

    v_dv      := std_logic(to_unsigned(i_dv, 1)(0));
    v_header  := std_logic(to_unsigned(i_header, 1)(0));
    v_trailer := std_logic(to_unsigned(i_trailer, 1)(0));
    VALUE := (
      data    => v_data,
      dv      => v_dv,
      header  => v_header,
      trailer => v_trailer);
  end READ;



  -- <ESH> NEW hex output
  procedure WRITE(L : inout line; VALUE : in felix_out_rt) is

    variable v_data    : std_logic_vector(len4r(FELIX_OUT_DATA_LEN)-1 downto 0);
    variable v_dv      : std_logic;
    variable v_header  : std_logic;
    variable v_trailer : std_logic;

  begin

    v_data(FELIX_OUT_DATA_LEN-1 downto 0) := VALUE.data;
    v_dv                                  := VALUE.dv;
    v_header                              := VALUE.header;
    v_trailer                             := VALUE.trailer;

    HWRITE(L, v_data);
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned'("" & v_dv)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned'("" & v_header)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned'("" & v_trailer)));
  end WRITE;


  procedure READ(L : inout line; VALUE : out slc_muid_rt) is
    variable i_slcid : integer;
    variable i_slid  : integer;
    variable i_bcid  : integer;

    variable v_slcid : std_logic_vector(SLC_MUID_SLCID_LEN-1 downto 0);
    variable v_slid  : std_logic_vector(SLC_MUID_SLID_LEN-1 downto 0);
    variable v_bcid  : std_logic_vector(SLC_MUID_BCID_LEN-1 downto 0);

    variable v_SPACE : character;

  begin

    READ(L, i_slcid);
    READ(L, v_SPACE);
    READ(L, i_slid);
    READ(L, v_SPACE);
    READ(L, i_bcid);

    v_slcid := std_logic_vector(to_unsigned(i_slcid, SLC_MUID_SLCID_LEN));
    v_slid  := std_logic_vector(to_unsigned(i_slid, SLC_MUID_SLID_LEN));
    v_bcid  := std_logic_vector(to_unsigned(i_bcid, SLC_MUID_BCID_LEN));
    VALUE := (
      slcid => v_slcid,
      slid  => v_slid,
      bcid  => v_bcid);
  end READ;



  procedure WRITE(L : inout line; VALUE : in slc_muid_rt) is

    variable v_slcid : std_logic_vector(SLC_MUID_SLCID_LEN-1 downto 0);
    variable v_slid  : std_logic_vector(SLC_MUID_SLID_LEN-1 downto 0);
    variable v_bcid  : std_logic_vector(SLC_MUID_BCID_LEN-1 downto 0);

  begin

    v_slcid := VALUE.slcid;
    v_slid  := VALUE.slid;
    v_bcid  := VALUE.bcid;
    WRITE(L, to_integer(unsigned(v_slcid)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_slid)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_bcid)));
  end WRITE;


  procedure READ(L : inout line; VALUE : out slc_common_rt) is
    variable i_slcid    : integer;
    variable i_tcsent   : integer;
    variable i_poseta   : integer;
    variable i_posphi   : integer;
    variable i_ptthresh : integer;
    variable i_charge   : integer;

    variable v_slcid    : std_logic_vector(SLC_COMMON_SLCID_LEN-1 downto 0);
    variable v_tcsent   : std_logic;
    variable v_poseta   : std_logic_vector(SLC_COMMON_POSETA_LEN-1 downto 0);
    variable v_posphi   : std_logic_vector(SLC_COMMON_POSPHI_LEN-1 downto 0);
    variable v_ptthresh : std_logic_vector(SLC_COMMON_PTTHRESH_LEN-1 downto 0);
    variable v_charge   : std_logic;

    variable v_SPACE : character;

  begin

    READ(L, i_slcid);
    READ(L, v_SPACE);
    READ(L, i_tcsent);
    READ(L, v_SPACE);
    READ(L, i_poseta);
    READ(L, v_SPACE);
    READ(L, i_posphi);
    READ(L, v_SPACE);
    READ(L, i_ptthresh);
    READ(L, v_SPACE);
    READ(L, i_charge);

    v_slcid    := std_logic_vector(to_unsigned(i_slcid, SLC_COMMON_SLCID_LEN));
    v_tcsent   := std_logic(to_unsigned(i_tcsent, 1)(0));
    v_poseta   := std_logic_vector(to_unsigned(i_poseta, SLC_COMMON_POSETA_LEN));
    v_posphi   := std_logic_vector(to_unsigned(i_posphi, SLC_COMMON_POSPHI_LEN));
    v_ptthresh := std_logic_vector(to_unsigned(i_ptthresh, SLC_COMMON_PTTHRESH_LEN));
    v_charge   := std_logic(to_unsigned(i_charge, 1)(0));
    VALUE := (
      slcid    => v_slcid,
      tcsent   => v_tcsent,
      poseta   => v_poseta,
      posphi   => v_posphi,
      ptthresh => v_ptthresh,
      charge   => v_charge);
  end READ;



  procedure WRITE(L : inout line; VALUE : in slc_common_rt) is

    variable v_slcid    : std_logic_vector(SLC_COMMON_SLCID_LEN-1 downto 0);
    variable v_tcsent   : std_logic;
    variable v_poseta   : std_logic_vector(SLC_COMMON_POSETA_LEN-1 downto 0);
    variable v_posphi   : std_logic_vector(SLC_COMMON_POSPHI_LEN-1 downto 0);
    variable v_ptthresh : std_logic_vector(SLC_COMMON_PTTHRESH_LEN-1 downto 0);
    variable v_charge   : std_logic;

  begin

    v_slcid    := VALUE.slcid;
    v_tcsent   := VALUE.tcsent;
    v_poseta   := VALUE.poseta;
    v_posphi   := VALUE.posphi;
    v_ptthresh := VALUE.ptthresh;
    v_charge   := VALUE.charge;
    WRITE(L, to_integer(unsigned(v_slcid)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned'("" & v_tcsent)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_poseta)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_posphi)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_ptthresh)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned'("" & v_charge)));
  end WRITE;


  procedure READ(L : inout line; VALUE : out slc_endcap_rt) is
    variable i_seg_angdtheta    : integer;
    variable i_seg_angdphi      : integer;
    variable i_nswseg_poseta    : integer;
    variable i_nswseg_posphi    : integer;
    variable i_nswseg_angdtheta : integer;

    variable v_slc_common_r     : SLC_COMMON_rt;
    variable v_seg_angdtheta    : std_logic_vector(SLC_ENDCAP_SEG_ANGDTHETA_LEN-1 downto 0);
    variable v_seg_angdphi      : std_logic_vector(SLC_ENDCAP_SEG_ANGDPHI_LEN-1 downto 0);
    variable v_nswseg_poseta    : std_logic_vector(SLC_ENDCAP_NSWSEG_POSETA_LEN-1 downto 0);
    variable v_nswseg_posphi    : std_logic_vector(SLC_ENDCAP_NSWSEG_POSPHI_LEN-1 downto 0);
    variable v_nswseg_angdtheta : std_logic_vector(SLC_ENDCAP_NSWSEG_ANGDTHETA_LEN-1 downto 0);

    variable v_SPACE : character;

  begin

    READ(L, v_slc_common_r);
    READ(L, v_SPACE);
    READ(L, i_seg_angdtheta);
    READ(L, v_SPACE);
    READ(L, i_seg_angdphi);
    READ(L, v_SPACE);
    READ(L, i_nswseg_poseta);
    READ(L, v_SPACE);
    READ(L, i_nswseg_posphi);
    READ(L, v_SPACE);
    READ(L, i_nswseg_angdtheta);

    v_seg_angdtheta    := std_logic_vector(to_unsigned(i_seg_angdtheta, SLC_ENDCAP_SEG_ANGDTHETA_LEN));
    v_seg_angdphi      := std_logic_vector(to_unsigned(i_seg_angdphi, SLC_ENDCAP_SEG_ANGDPHI_LEN));
    v_nswseg_poseta    := std_logic_vector(to_unsigned(i_nswseg_poseta, SLC_ENDCAP_NSWSEG_POSETA_LEN));
    v_nswseg_posphi    := std_logic_vector(to_unsigned(i_nswseg_posphi, SLC_ENDCAP_NSWSEG_POSPHI_LEN));
    v_nswseg_angdtheta := std_logic_vector(to_unsigned(i_nswseg_angdtheta, SLC_ENDCAP_NSWSEG_ANGDTHETA_LEN));
    VALUE := (
      slc_common_r     => v_slc_common_r,
      seg_angdtheta    => v_seg_angdtheta,
      seg_angdphi      => v_seg_angdphi,
      nswseg_poseta    => v_nswseg_poseta,
      nswseg_posphi    => v_nswseg_posphi,
      nswseg_angdtheta => v_nswseg_angdtheta);
  end READ;



  procedure WRITE(L : inout line; VALUE : in slc_endcap_rt) is

    variable v_slc_common_r     : SLC_COMMON_rt;
    variable v_seg_angdtheta    : std_logic_vector(SLC_ENDCAP_SEG_ANGDTHETA_LEN-1 downto 0);
    variable v_seg_angdphi      : std_logic_vector(SLC_ENDCAP_SEG_ANGDPHI_LEN-1 downto 0);
    variable v_nswseg_poseta    : std_logic_vector(SLC_ENDCAP_NSWSEG_POSETA_LEN-1 downto 0);
    variable v_nswseg_posphi    : std_logic_vector(SLC_ENDCAP_NSWSEG_POSPHI_LEN-1 downto 0);
    variable v_nswseg_angdtheta : std_logic_vector(SLC_ENDCAP_NSWSEG_ANGDTHETA_LEN-1 downto 0);

  begin

    v_slc_common_r     := VALUE.slc_common_r;
    v_seg_angdtheta    := VALUE.seg_angdtheta;
    v_seg_angdphi      := VALUE.seg_angdphi;
    v_nswseg_poseta    := VALUE.nswseg_poseta;
    v_nswseg_posphi    := VALUE.nswseg_posphi;
    v_nswseg_angdtheta := VALUE.nswseg_angdtheta;
    WRITE(L, v_slc_common_r);
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_seg_angdtheta)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_seg_angdphi)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_nswseg_poseta)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_nswseg_posphi)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_nswseg_angdtheta)));
  end WRITE;


  procedure READ(L : inout line; VALUE : out slc_barrel_rt) is
    variable i_rpc0_posz : integer;
    variable i_rpc1_posz : integer;
    variable i_rpc2_posz : integer;
    variable i_rpc3_posz : integer;
    variable i_cointype  : integer;

    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_rpc0_posz    : std_logic_vector(SLC_BARREL_RPC0_POSZ_LEN-1 downto 0);
    variable v_rpc1_posz    : std_logic_vector(SLC_BARREL_RPC1_POSZ_LEN-1 downto 0);
    variable v_rpc2_posz    : std_logic_vector(SLC_BARREL_RPC2_POSZ_LEN-1 downto 0);
    variable v_rpc3_posz    : std_logic_vector(SLC_BARREL_RPC3_POSZ_LEN-1 downto 0);
    variable v_cointype     : std_logic_vector(SLC_BARREL_COINTYPE_LEN-1 downto 0);

    variable v_SPACE : character;

  begin

    READ(L, v_slc_common_r);
    READ(L, v_SPACE);
    READ(L, i_rpc0_posz);
    READ(L, v_SPACE);
    READ(L, i_rpc1_posz);
    READ(L, v_SPACE);
    READ(L, i_rpc2_posz);
    READ(L, v_SPACE);
    READ(L, i_rpc3_posz);
    READ(L, v_SPACE);
    READ(L, i_cointype);

    v_rpc0_posz := std_logic_vector(to_unsigned(i_rpc0_posz, SLC_BARREL_RPC0_POSZ_LEN));
    v_rpc1_posz := std_logic_vector(to_unsigned(i_rpc1_posz, SLC_BARREL_RPC1_POSZ_LEN));
    v_rpc2_posz := std_logic_vector(to_unsigned(i_rpc2_posz, SLC_BARREL_RPC2_POSZ_LEN));
    v_rpc3_posz := std_logic_vector(to_unsigned(i_rpc3_posz, SLC_BARREL_RPC3_POSZ_LEN));
    v_cointype  := std_logic_vector(to_unsigned(i_cointype, SLC_BARREL_COINTYPE_LEN));
    VALUE := (
      slc_common_r => v_slc_common_r,
      rpc0_posz    => v_rpc0_posz,
      rpc1_posz    => v_rpc1_posz,
      rpc2_posz    => v_rpc2_posz,
      rpc3_posz    => v_rpc3_posz,
      cointype     => v_cointype);
  end READ;



  procedure WRITE(L : inout line; VALUE : in slc_barrel_rt) is

    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_rpc0_posz    : std_logic_vector(SLC_BARREL_RPC0_POSZ_LEN-1 downto 0);
    variable v_rpc1_posz    : std_logic_vector(SLC_BARREL_RPC1_POSZ_LEN-1 downto 0);
    variable v_rpc2_posz    : std_logic_vector(SLC_BARREL_RPC2_POSZ_LEN-1 downto 0);
    variable v_rpc3_posz    : std_logic_vector(SLC_BARREL_RPC3_POSZ_LEN-1 downto 0);
    variable v_cointype     : std_logic_vector(SLC_BARREL_COINTYPE_LEN-1 downto 0);

  begin

    v_slc_common_r := VALUE.slc_common_r;
    v_rpc0_posz    := VALUE.rpc0_posz;
    v_rpc1_posz    := VALUE.rpc1_posz;
    v_rpc2_posz    := VALUE.rpc2_posz;
    v_rpc3_posz    := VALUE.rpc3_posz;
    v_cointype     := VALUE.cointype;
    WRITE(L, v_slc_common_r);
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_rpc0_posz)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_rpc1_posz)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_rpc2_posz)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_rpc3_posz)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_cointype)));
  end WRITE;


  procedure READ(L : inout line; VALUE : out slcproc_pipe_common_rt) is
    variable i_busy          : integer;
    variable i_destsl        : integer;
    variable i_phimod        : integer;
    variable i_inn_vec_mdtid : integer;
    variable i_mid_vec_mdtid : integer;
    variable i_out_vec_mdtid : integer;
    variable i_ext_vec_mdtid : integer;

    variable v_busy          : std_logic;
    variable v_destsl        : std_logic_vector(SLCPROC_PIPE_COMMON_DESTSL_LEN-1 downto 0);
    variable v_phimod        : std_logic_vector(SLCPROC_PIPE_COMMON_PHIMOD_LEN-1 downto 0);
    variable v_inn_vec_mdtid : std_logic_vector(SLCPROC_PIPE_COMMON_INN_VEC_MDTID_LEN-1 downto 0);
    variable v_mid_vec_mdtid : std_logic_vector(SLCPROC_PIPE_COMMON_MID_VEC_MDTID_LEN-1 downto 0);
    variable v_out_vec_mdtid : std_logic_vector(SLCPROC_PIPE_COMMON_OUT_VEC_MDTID_LEN-1 downto 0);
    variable v_ext_vec_mdtid : std_logic_vector(SLCPROC_PIPE_COMMON_EXT_VEC_MDTID_LEN-1 downto 0);

    variable v_SPACE : character;

  begin

    READ(L, i_busy);
    READ(L, v_SPACE);
    READ(L, i_destsl);
    READ(L, v_SPACE);
    READ(L, i_phimod);
    READ(L, v_SPACE);
    READ(L, i_inn_vec_mdtid);
    READ(L, v_SPACE);
    READ(L, i_mid_vec_mdtid);
    READ(L, v_SPACE);
    READ(L, i_out_vec_mdtid);
    READ(L, v_SPACE);
    READ(L, i_ext_vec_mdtid);

    v_busy          := std_logic(to_unsigned(i_busy, 1)(0));
    v_destsl        := std_logic_vector(to_unsigned(i_destsl, SLCPROC_PIPE_COMMON_DESTSL_LEN));
    v_phimod        := std_logic_vector(to_unsigned(i_phimod, SLCPROC_PIPE_COMMON_PHIMOD_LEN));
    v_inn_vec_mdtid := std_logic_vector(to_unsigned(i_inn_vec_mdtid, SLCPROC_PIPE_COMMON_INN_VEC_MDTID_LEN));
    v_mid_vec_mdtid := std_logic_vector(to_unsigned(i_mid_vec_mdtid, SLCPROC_PIPE_COMMON_MID_VEC_MDTID_LEN));
    v_out_vec_mdtid := std_logic_vector(to_unsigned(i_out_vec_mdtid, SLCPROC_PIPE_COMMON_OUT_VEC_MDTID_LEN));
    v_ext_vec_mdtid := std_logic_vector(to_unsigned(i_ext_vec_mdtid, SLCPROC_PIPE_COMMON_EXT_VEC_MDTID_LEN));
    VALUE := (
      busy          => v_busy,
      destsl        => v_destsl,
      phimod        => v_phimod,
      inn_vec_mdtid => v_inn_vec_mdtid,
      mid_vec_mdtid => v_mid_vec_mdtid,
      out_vec_mdtid => v_out_vec_mdtid,
      ext_vec_mdtid => v_ext_vec_mdtid);
  end READ;



  procedure WRITE(L : inout line; VALUE : in slcproc_pipe_common_rt) is

    variable v_busy          : std_logic;
    variable v_destsl        : std_logic_vector(SLCPROC_PIPE_COMMON_DESTSL_LEN-1 downto 0);
    variable v_phimod        : std_logic_vector(SLCPROC_PIPE_COMMON_PHIMOD_LEN-1 downto 0);
    variable v_inn_vec_mdtid : std_logic_vector(SLCPROC_PIPE_COMMON_INN_VEC_MDTID_LEN-1 downto 0);
    variable v_mid_vec_mdtid : std_logic_vector(SLCPROC_PIPE_COMMON_MID_VEC_MDTID_LEN-1 downto 0);
    variable v_out_vec_mdtid : std_logic_vector(SLCPROC_PIPE_COMMON_OUT_VEC_MDTID_LEN-1 downto 0);
    variable v_ext_vec_mdtid : std_logic_vector(SLCPROC_PIPE_COMMON_EXT_VEC_MDTID_LEN-1 downto 0);

  begin

    v_busy          := VALUE.busy;
    v_destsl        := VALUE.destsl;
    v_phimod        := VALUE.phimod;
    v_inn_vec_mdtid := VALUE.inn_vec_mdtid;
    v_mid_vec_mdtid := VALUE.mid_vec_mdtid;
    v_out_vec_mdtid := VALUE.out_vec_mdtid;
    v_ext_vec_mdtid := VALUE.ext_vec_mdtid;
    WRITE(L, to_integer(unsigned'("" & v_busy)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_destsl)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_phimod)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_inn_vec_mdtid)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_mid_vec_mdtid)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_out_vec_mdtid)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_ext_vec_mdtid)));
  end WRITE;


  procedure READ(L : inout line; VALUE : out slcproc_pipe_endcap_rt) is

    variable v_slcproc_pipe_common_r : SLCPROC_PIPE_COMMON_rt;
    variable v_slc_endcap_r          : SLC_ENDCAP_rt;
    variable v_slc_muid_r            : SLC_MUID_rt;

    variable v_SPACE : character;

  begin

    READ(L, v_slcproc_pipe_common_r);
    READ(L, v_SPACE);
    READ(L, v_slc_endcap_r);
    READ(L, v_SPACE);
    READ(L, v_slc_muid_r);

    VALUE := (
      slcproc_pipe_common_r => v_slcproc_pipe_common_r,
      slc_endcap_r          => v_slc_endcap_r,
      slc_muid_r            => v_slc_muid_r);
  end READ;



  procedure WRITE(L : inout line; VALUE : in slcproc_pipe_endcap_rt) is

    variable v_slcproc_pipe_common_r : SLCPROC_PIPE_COMMON_rt;
    variable v_slc_endcap_r          : SLC_ENDCAP_rt;
    variable v_slc_muid_r            : SLC_MUID_rt;

  begin

    v_slcproc_pipe_common_r := VALUE.slcproc_pipe_common_r;
    v_slc_endcap_r          := VALUE.slc_endcap_r;
    v_slc_muid_r            := VALUE.slc_muid_r;
    WRITE(L, v_slcproc_pipe_common_r);
    WRITE(L, ' ');
    WRITE(L, v_slc_endcap_r);
    WRITE(L, ' ');
    WRITE(L, v_slc_muid_r);
  end WRITE;


  procedure READ(L : inout line; VALUE : out slcproc_pipe_barrel_rt) is

    variable v_slcproc_pipe_common_r : SLCPROC_PIPE_COMMON_rt;
    variable v_slc_barrel_r          : SLC_BARREL_rt;
    variable v_slc_muid_r            : SLC_MUID_rt;

    variable v_SPACE : character;

  begin

    READ(L, v_slcproc_pipe_common_r);
    READ(L, v_SPACE);
    READ(L, v_slc_barrel_r);
    READ(L, v_SPACE);
    READ(L, v_slc_muid_r);

    VALUE := (
      slcproc_pipe_common_r => v_slcproc_pipe_common_r,
      slc_barrel_r          => v_slc_barrel_r,
      slc_muid_r            => v_slc_muid_r);
  end READ;



  procedure WRITE(L : inout line; VALUE : in slcproc_pipe_barrel_rt) is

    variable v_slcproc_pipe_common_r : SLCPROC_PIPE_COMMON_rt;
    variable v_slc_barrel_r          : SLC_BARREL_rt;
    variable v_slc_muid_r            : SLC_MUID_rt;

  begin

    v_slcproc_pipe_common_r := VALUE.slcproc_pipe_common_r;
    v_slc_barrel_r          := VALUE.slc_barrel_r;
    v_slc_muid_r            := VALUE.slc_muid_r;
    WRITE(L, v_slcproc_pipe_common_r);
    WRITE(L, ' ');
    WRITE(L, v_slc_barrel_r);
    WRITE(L, ' ');
    WRITE(L, v_slc_muid_r);
  end WRITE;

  procedure READ(L : inout line; VALUE : out tdc_rt) is

    variable v_chanid     : std_logic_vector(len4r(TDC_CHANID_LEN)-1 downto 0);
    variable v_edgemode   : std_logic_vector(len4r(TDC_EDGEMODE_LEN)-1 downto 0);
    variable v_coarsetime : std_logic_vector(len4r(TDC_COARSETIME_LEN)-1 downto 0);
    variable v_finetime   : std_logic_vector(len4r(TDC_FINETIME_LEN)-1 downto 0);
    variable v_pulsewidth : std_logic_vector(len4r(TDC_PULSEWIDTH_LEN)-1 downto 0);

    variable v_SPACE : character;

  begin

    -- hex version
    HREAD(L, v_chanid);
    READ(L, v_SPACE);
    HREAD(L, v_edgemode);
    READ(L, v_SPACE);
    HREAD(L, v_coarsetime);
    READ(L, v_SPACE);
    HREAD(L, v_finetime);
    READ(L, v_SPACE);
    HREAD(L, v_pulsewidth);

    VALUE := (
      chanid     => v_chanid(TDC_CHANID_LEN-1 downto 0),
      edgemode   => v_edgemode(TDC_EDGEMODE_LEN-1 downto 0),
      coarsetime => v_coarsetime(TDC_COARSETIME_LEN-1 downto 0),
      finetime   => v_finetime(TDC_FINETIME_LEN-1 downto 0),
      pulsewidth => v_pulsewidth(TDC_PULSEWIDTH_LEN-1 downto 0));

  end READ;



  procedure WRITE(L : inout line; VALUE : in tdc_rt) is

    variable v_chanid     : std_logic_vector(TDC_CHANID_LEN-1 downto 0);
    variable v_edgemode   : std_logic_vector(TDC_EDGEMODE_LEN-1 downto 0);
    variable v_coarsetime : std_logic_vector(TDC_COARSETIME_LEN-1 downto 0);
    variable v_finetime   : std_logic_vector(TDC_FINETIME_LEN-1 downto 0);
    variable v_pulsewidth : std_logic_vector(TDC_PULSEWIDTH_LEN-1 downto 0);

  begin

    v_chanid     := VALUE.chanid;
    v_edgemode   := VALUE.edgemode;
    v_coarsetime := VALUE.coarsetime;
    v_finetime   := VALUE.finetime;
    v_pulsewidth := VALUE.pulsewidth;
    WRITE(L, to_integer(unsigned(v_chanid)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_edgemode)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_coarsetime)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_finetime)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_pulsewidth)));
  end WRITE;


  procedure READ(L : inout line; VALUE : out tdcpolmux_rt) is
    variable i_fiberid   : integer;
    variable i_elinkid   : integer;
    variable i_datavalid : integer;

    variable v_tdc_r     : TDC_rt;
    variable v_fiberid   : std_logic_vector(len4r(TDCPOLMUX_FIBERID_LEN)-1 downto 0);
    variable v_elinkid   : std_logic_vector(len4r(TDCPOLMUX_ELINKID_LEN)-1 downto 0);
    variable v_datavalid : std_logic;

    variable v_SPACE : character;

    variable buff : line;

  begin

    READ(L, v_tdc_r);

    READ(L, v_SPACE);

--    write(buff,string'("TDC read complete"));
--    writeline(output,buff);
--    write(buff,string'("Separator seen: ["));
--    write(buff,v_SPACE);
--    write(buff,']');
--    writeline(output,buff);
--
--    write( buff, string'("Try read v_fiberid size: "));
--    write( buff, len4r(TDCPOLMUX_FIBERID_LEN));
--    writeline( output, buff);

    HREAD(L, v_fiberid);
    READ(L, v_SPACE);

--    write( buff, string'("Try read v_elinkid size: "));
--    write( buff, len4r(TDCPOLMUX_ELINKID_LEN));
--    writeline( output, buff);
    HREAD(L, v_elinkid);
    READ(L, v_SPACE);
    READ(L, v_datavalid);

--    v_datavalid := std_logic(to_unsigned(i_datavalid, 1)(0));
    VALUE := (
      tdc_r     => v_tdc_r,
      fiberid   => v_fiberid(TDCPOLMUX_FIBERID_LEN-1 downto 0),
      elinkid   => v_elinkid(TDCPOLMUX_ELINKID_LEN-1 downto 0),
      datavalid => v_datavalid);
  end READ;



  procedure WRITE(L : inout line; VALUE : in tdcpolmux_rt) is

    variable v_tdc_r     : TDC_rt;
    variable v_fiberid   : std_logic_vector(TDCPOLMUX_FIBERID_LEN-1 downto 0);
    variable v_elinkid   : std_logic_vector(TDCPOLMUX_ELINKID_LEN-1 downto 0);
    variable v_datavalid : std_logic;

  begin

    v_tdc_r     := VALUE.tdc_r;
    v_fiberid   := VALUE.fiberid;
    v_elinkid   := VALUE.elinkid;
    v_datavalid := VALUE.datavalid;
    WRITE(L, v_tdc_r);
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_fiberid)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_elinkid)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned'("" & v_datavalid)));
  end WRITE;


  procedure READ(L : inout line; VALUE : out slcproc_hps_sf_rt) is
    variable i_slc_valid   : integer;
    variable i_mdtseg_dest : integer;
    variable i_vec_mdtid   : integer;
    variable i_vec_pos     : integer;
    variable i_vec_ang     : integer;

    variable v_slc_valid   : std_logic;
    variable v_slc_muid_r  : SLC_MUID_rt;
    variable v_mdtseg_dest : std_logic_vector(SLCPROC_HPS_SF_MDTSEG_DEST_LEN-1 downto 0);
    variable v_vec_mdtid   : std_logic_vector(SLCPROC_HPS_SF_VEC_MDTID_LEN-1 downto 0);
    variable v_vec_pos     : std_logic_vector(SLCPROC_HPS_SF_VEC_POS_LEN-1 downto 0);
    variable v_vec_ang     : std_logic_vector(SLCPROC_HPS_SF_VEC_ANG_LEN-1 downto 0);

    variable v_SPACE : character;

  begin

    READ(L, i_slc_valid);
    READ(L, v_SPACE);
    READ(L, v_slc_muid_r);
    READ(L, v_SPACE);
    READ(L, i_mdtseg_dest);
    READ(L, v_SPACE);
    READ(L, i_vec_mdtid);
    READ(L, v_SPACE);
    READ(L, i_vec_pos);
    READ(L, v_SPACE);
    READ(L, i_vec_ang);

    v_slc_valid   := std_logic(to_unsigned(i_slc_valid, 1)(0));
    v_mdtseg_dest := std_logic_vector(to_unsigned(i_mdtseg_dest, SLCPROC_HPS_SF_MDTSEG_DEST_LEN));
    v_vec_mdtid   := std_logic_vector(to_unsigned(i_vec_mdtid, SLCPROC_HPS_SF_VEC_MDTID_LEN));
    v_vec_pos     := std_logic_vector(to_unsigned(i_vec_pos, SLCPROC_HPS_SF_VEC_POS_LEN));
    v_vec_ang     := std_logic_vector(to_unsigned(i_vec_ang, SLCPROC_HPS_SF_VEC_ANG_LEN));
    VALUE := (
      slc_valid   => v_slc_valid,
      slc_muid_r  => v_slc_muid_r,
      mdtseg_dest => v_mdtseg_dest,
      vec_mdtid   => v_vec_mdtid,
      vec_pos     => v_vec_pos,
      vec_ang     => v_vec_ang);
  end READ;



  procedure WRITE(L : inout line; VALUE : in slcproc_hps_sf_rt) is

    variable v_slc_valid   : std_logic;
    variable v_slc_muid_r  : SLC_MUID_rt;
    variable v_mdtseg_dest : std_logic_vector(SLCPROC_HPS_SF_MDTSEG_DEST_LEN-1 downto 0);
    variable v_vec_mdtid   : std_logic_vector(SLCPROC_HPS_SF_VEC_MDTID_LEN-1 downto 0);
    variable v_vec_pos     : std_logic_vector(SLCPROC_HPS_SF_VEC_POS_LEN-1 downto 0);
    variable v_vec_ang     : std_logic_vector(SLCPROC_HPS_SF_VEC_ANG_LEN-1 downto 0);

  begin

    v_slc_valid   := VALUE.slc_valid;
    v_slc_muid_r  := VALUE.slc_muid_r;
    v_mdtseg_dest := VALUE.mdtseg_dest;
    v_vec_mdtid   := VALUE.vec_mdtid;
    v_vec_pos     := VALUE.vec_pos;
    v_vec_ang     := VALUE.vec_ang;
    WRITE(L, to_integer(unsigned'("" & v_slc_valid)));
    WRITE(L, ' ');
    WRITE(L, v_slc_muid_r);
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_mdtseg_dest)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_vec_mdtid)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_vec_pos)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_vec_ang)));
  end WRITE;


  procedure READ(L : inout line; VALUE : out tar_rt) is
    variable i_mdt_tube_layer : integer;
    variable i_mdt_tube_num   : integer;
    variable i_mdt_tube_rho   : integer;
    variable i_mdt_tube_z     : integer;
    variable i_mdt_tube_time  : integer;

    variable v_mdt_tube_layer : std_logic_vector(TAR_MDT_TUBE_LAYER_LEN-1 downto 0);
    variable v_mdt_tube_num   : std_logic_vector(TAR_MDT_TUBE_NUM_LEN-1 downto 0);
    variable v_mdt_tube_rho   : std_logic_vector(TAR_MDT_TUBE_RHO_LEN-1 downto 0);
    variable v_mdt_tube_z     : std_logic_vector(TAR_MDT_TUBE_Z_LEN-1 downto 0);
    variable v_mdt_tube_time  : std_logic_vector(TAR_MDT_TUBE_TIME_LEN-1 downto 0);

    variable v_SPACE : character;

  begin

    READ(L, i_mdt_tube_layer);
    READ(L, v_SPACE);
    READ(L, i_mdt_tube_num);
    READ(L, v_SPACE);
    READ(L, i_mdt_tube_rho);
    READ(L, v_SPACE);
    READ(L, i_mdt_tube_z);
    READ(L, v_SPACE);
    READ(L, i_mdt_tube_time);

    v_mdt_tube_layer := std_logic_vector(to_unsigned(i_mdt_tube_layer, TAR_MDT_TUBE_LAYER_LEN));
    v_mdt_tube_num   := std_logic_vector(to_unsigned(i_mdt_tube_num, TAR_MDT_TUBE_NUM_LEN));
    v_mdt_tube_rho   := std_logic_vector(to_unsigned(i_mdt_tube_rho, TAR_MDT_TUBE_RHO_LEN));
    v_mdt_tube_z     := std_logic_vector(to_unsigned(i_mdt_tube_z, TAR_MDT_TUBE_Z_LEN));
    v_mdt_tube_time  := std_logic_vector(to_unsigned(i_mdt_tube_time, TAR_MDT_TUBE_TIME_LEN));
    VALUE := (
      mdt_tube_layer => v_mdt_tube_layer,
      mdt_tube_num   => v_mdt_tube_num,
      mdt_tube_rho   => v_mdt_tube_rho,
      mdt_tube_z     => v_mdt_tube_z,
      mdt_tube_time  => v_mdt_tube_time);
  end READ;



  procedure WRITE(L : inout line; VALUE : in tar_rt) is

    variable v_mdt_tube_layer : std_logic_vector(TAR_MDT_TUBE_LAYER_LEN-1 downto 0);
    variable v_mdt_tube_num   : std_logic_vector(TAR_MDT_TUBE_NUM_LEN-1 downto 0);
    variable v_mdt_tube_rho   : std_logic_vector(TAR_MDT_TUBE_RHO_LEN-1 downto 0);
    variable v_mdt_tube_z     : std_logic_vector(TAR_MDT_TUBE_Z_LEN-1 downto 0);
    variable v_mdt_tube_time  : std_logic_vector(TAR_MDT_TUBE_TIME_LEN-1 downto 0);

  begin

    v_mdt_tube_layer := VALUE.mdt_tube_layer;
    v_mdt_tube_num   := VALUE.mdt_tube_num;
    v_mdt_tube_rho   := VALUE.mdt_tube_rho;
    v_mdt_tube_z     := VALUE.mdt_tube_z;
    v_mdt_tube_time  := VALUE.mdt_tube_time;
    WRITE(L, to_integer(unsigned(v_mdt_tube_layer)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_mdt_tube_num)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_mdt_tube_rho)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_mdt_tube_z)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_mdt_tube_time)));
  end WRITE;


  procedure READ(L : inout line; VALUE : out hps_lsf_rt) is
    variable i_data_valid : integer;
    variable i_mdt_localx : integer;
    variable i_mdt_localy : integer;
    variable i_mdt_radius : integer;

    variable v_data_valid : std_logic;
    variable v_mdt_localx : std_logic_vector(HPS_LSF_MDT_LOCALX_LEN-1 downto 0);
    variable v_mdt_localy : std_logic_vector(HPS_LSF_MDT_LOCALY_LEN-1 downto 0);
    variable v_mdt_radius : std_logic_vector(HPS_LSF_MDT_RADIUS_LEN-1 downto 0);

    variable v_SPACE : character;

  begin

    READ(L, i_data_valid);
    READ(L, v_SPACE);
    READ(L, i_mdt_localx);
    READ(L, v_SPACE);
    READ(L, i_mdt_localy);
    READ(L, v_SPACE);
    READ(L, i_mdt_radius);

    v_data_valid := std_logic(to_unsigned(i_data_valid, 1)(0));
    v_mdt_localx := std_logic_vector(to_unsigned(i_mdt_localx, HPS_LSF_MDT_LOCALX_LEN));
    v_mdt_localy := std_logic_vector(to_unsigned(i_mdt_localy, HPS_LSF_MDT_LOCALY_LEN));
    v_mdt_radius := std_logic_vector(to_unsigned(i_mdt_radius, HPS_LSF_MDT_RADIUS_LEN));
    VALUE := (
      data_valid => v_data_valid,
      mdt_localx => v_mdt_localx,
      mdt_localy => v_mdt_localy,
      mdt_radius => v_mdt_radius);
  end READ;



  procedure WRITE(L : inout line; VALUE : in hps_lsf_rt) is

    variable v_data_valid : std_logic;
    variable v_mdt_localx : std_logic_vector(HPS_LSF_MDT_LOCALX_LEN-1 downto 0);
    variable v_mdt_localy : std_logic_vector(HPS_LSF_MDT_LOCALY_LEN-1 downto 0);
    variable v_mdt_radius : std_logic_vector(HPS_LSF_MDT_RADIUS_LEN-1 downto 0);

  begin

    v_data_valid := VALUE.data_valid;
    v_mdt_localx := VALUE.mdt_localx;
    v_mdt_localy := VALUE.mdt_localy;
    v_mdt_radius := VALUE.mdt_radius;
    WRITE(L, to_integer(unsigned'("" & v_data_valid)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_mdt_localx)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_mdt_localy)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_mdt_radius)));
  end WRITE;


  procedure READ(L : inout line; VALUE : out hps_csf_rt) is
    variable i_data_valid : integer;
    variable i_mdt_localx : integer;
    variable i_mdt_localy : integer;
    variable i_mdt_radius : integer;

    variable v_data_valid : std_logic;
    variable v_mdt_localx : std_logic_vector(HPS_CSF_MDT_LOCALX_LEN-1 downto 0);
    variable v_mdt_localy : std_logic_vector(HPS_CSF_MDT_LOCALY_LEN-1 downto 0);
    variable v_mdt_radius : std_logic_vector(HPS_CSF_MDT_RADIUS_LEN-1 downto 0);

    variable v_SPACE : character;

  begin

    READ(L, i_data_valid);
    READ(L, v_SPACE);
    READ(L, i_mdt_localx);
    READ(L, v_SPACE);
    READ(L, i_mdt_localy);
    READ(L, v_SPACE);
    READ(L, i_mdt_radius);

    v_data_valid := std_logic(to_unsigned(i_data_valid, 1)(0));
    v_mdt_localx := std_logic_vector(to_unsigned(i_mdt_localx, HPS_CSF_MDT_LOCALX_LEN));
    v_mdt_localy := std_logic_vector(to_unsigned(i_mdt_localy, HPS_CSF_MDT_LOCALY_LEN));
    v_mdt_radius := std_logic_vector(to_unsigned(i_mdt_radius, HPS_CSF_MDT_RADIUS_LEN));
    VALUE := (
      data_valid => v_data_valid,
      mdt_localx => v_mdt_localx,
      mdt_localy => v_mdt_localy,
      mdt_radius => v_mdt_radius);
  end READ;



  procedure WRITE(L : inout line; VALUE : in hps_csf_rt) is

    variable v_data_valid : std_logic;
    variable v_mdt_localx : std_logic_vector(HPS_CSF_MDT_LOCALX_LEN-1 downto 0);
    variable v_mdt_localy : std_logic_vector(HPS_CSF_MDT_LOCALY_LEN-1 downto 0);
    variable v_mdt_radius : std_logic_vector(HPS_CSF_MDT_RADIUS_LEN-1 downto 0);

  begin

    v_data_valid := VALUE.data_valid;
    v_mdt_localx := VALUE.mdt_localx;
    v_mdt_localy := VALUE.mdt_localy;
    v_mdt_radius := VALUE.mdt_radius;
    WRITE(L, to_integer(unsigned'("" & v_data_valid)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_mdt_localx)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_mdt_localy)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_mdt_radius)));
  end WRITE;


  procedure READ(L : inout line; VALUE : out slcpipe_ptcalc_rt) is
    variable i_phimod : integer;
    variable i_charge : integer;

    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_phimod     : std_logic_vector(SLCPIPE_PTCALC_PHIMOD_LEN-1 downto 0);
    variable v_charge     : std_logic;

    variable v_SPACE : character;

  begin

    READ(L, v_slc_muid_r);
    READ(L, v_SPACE);
    READ(L, i_phimod);
    READ(L, v_SPACE);
    READ(L, i_charge);

    v_phimod := std_logic_vector(to_unsigned(i_phimod, SLCPIPE_PTCALC_PHIMOD_LEN));
    v_charge := std_logic(to_unsigned(i_charge, 1)(0));
    VALUE := (
      slc_muid_r => v_slc_muid_r,
      phimod     => v_phimod,
      charge     => v_charge);
  end READ;



  procedure WRITE(L : inout line; VALUE : in slcpipe_ptcalc_rt) is

    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_phimod     : std_logic_vector(SLCPIPE_PTCALC_PHIMOD_LEN-1 downto 0);
    variable v_charge     : std_logic;

  begin

    v_slc_muid_r := VALUE.slc_muid_r;
    v_phimod     := VALUE.phimod;
    v_charge     := VALUE.charge;
    WRITE(L, v_slc_muid_r);
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_phimod)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned'("" & v_charge)));
  end WRITE;


  procedure READ(L : inout line; VALUE : out sf_rt) is
    variable i_vec_mdtid  : integer;
    variable i_segvalid   : integer;
    variable i_segpos     : integer;
    variable i_segangle   : integer;
    variable i_segquality : integer;

    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_vec_mdtid  : std_logic_vector(SF_VEC_MDTID_LEN-1 downto 0);
    variable v_segvalid   : std_logic;
    variable v_segpos     : std_logic_vector(SF_SEGPOS_LEN-1 downto 0);
    variable v_segangle   : std_logic_vector(SF_SEGANGLE_LEN-1 downto 0);
    variable v_segquality : std_logic;

    variable v_SPACE : character;

  begin

    READ(L, v_slc_muid_r);
    READ(L, v_SPACE);
    READ(L, i_vec_mdtid);
    READ(L, v_SPACE);
    READ(L, i_segvalid);
    READ(L, v_SPACE);
    READ(L, i_segpos);
    READ(L, v_SPACE);
    READ(L, i_segangle);
    READ(L, v_SPACE);
    READ(L, i_segquality);

    v_vec_mdtid  := std_logic_vector(to_unsigned(i_vec_mdtid, SF_VEC_MDTID_LEN));
    v_segvalid   := std_logic(to_unsigned(i_segvalid, 1)(0));
    v_segpos     := std_logic_vector(to_unsigned(i_segpos, SF_SEGPOS_LEN));
    v_segangle   := std_logic_vector(to_unsigned(i_segangle, SF_SEGANGLE_LEN));
    v_segquality := std_logic(to_unsigned(i_segquality, 1)(0));
    VALUE := (
      slc_muid_r => v_slc_muid_r,
      vec_mdtid  => v_vec_mdtid,
      segvalid   => v_segvalid,
      segpos     => v_segpos,
      segangle   => v_segangle,
      segquality => v_segquality);
  end READ;



  procedure WRITE(L : inout line; VALUE : in sf_rt) is

    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_vec_mdtid  : std_logic_vector(SF_VEC_MDTID_LEN-1 downto 0);
    variable v_segvalid   : std_logic;
    variable v_segpos     : std_logic_vector(SF_SEGPOS_LEN-1 downto 0);
    variable v_segangle   : std_logic_vector(SF_SEGANGLE_LEN-1 downto 0);
    variable v_segquality : std_logic;

  begin

    v_slc_muid_r := VALUE.slc_muid_r;
    v_vec_mdtid  := VALUE.vec_mdtid;
    v_segvalid   := VALUE.segvalid;
    v_segpos     := VALUE.segpos;
    v_segangle   := VALUE.segangle;
    v_segquality := VALUE.segquality;
    WRITE(L, v_slc_muid_r);
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_vec_mdtid)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned'("" & v_segvalid)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_segpos)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_segangle)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned'("" & v_segquality)));
  end WRITE;


  procedure READ(L : inout line; VALUE : out ptcalc_rt) is
    variable i_eta       : integer;
    variable i_pt        : integer;
    variable i_ptthresh  : integer;
    variable i_charge    : integer;
    variable i_nsegments : integer;
    variable i_quality   : integer;

    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_eta        : std_logic_vector(PTCALC_ETA_LEN-1 downto 0);
    variable v_pt         : std_logic_vector(PTCALC_PT_LEN-1 downto 0);
    variable v_ptthresh   : std_logic_vector(PTCALC_PTTHRESH_LEN-1 downto 0);
    variable v_charge     : std_logic;
    variable v_nsegments  : std_logic_vector(PTCALC_NSEGMENTS_LEN-1 downto 0);
    variable v_quality    : std_logic_vector(PTCALC_QUALITY_LEN-1 downto 0);

    variable v_SPACE : character;

  begin

    READ(L, v_slc_muid_r);
    READ(L, v_SPACE);
    READ(L, i_eta);
    READ(L, v_SPACE);
    READ(L, i_pt);
    READ(L, v_SPACE);
    READ(L, i_ptthresh);
    READ(L, v_SPACE);
    READ(L, i_charge);
    READ(L, v_SPACE);
    READ(L, i_nsegments);
    READ(L, v_SPACE);
    READ(L, i_quality);

    v_eta       := std_logic_vector(to_unsigned(i_eta, PTCALC_ETA_LEN));
    v_pt        := std_logic_vector(to_unsigned(i_pt, PTCALC_PT_LEN));
    v_ptthresh  := std_logic_vector(to_unsigned(i_ptthresh, PTCALC_PTTHRESH_LEN));
    v_charge    := std_logic(to_unsigned(i_charge, 1)(0));
    v_nsegments := std_logic_vector(to_unsigned(i_nsegments, PTCALC_NSEGMENTS_LEN));
    v_quality   := std_logic_vector(to_unsigned(i_quality, PTCALC_QUALITY_LEN));
    VALUE := (
      slc_muid_r => v_slc_muid_r,
      eta        => v_eta,
      pt         => v_pt,
      ptthresh   => v_ptthresh,
      charge     => v_charge,
      nsegments  => v_nsegments,
      quality    => v_quality);
  end READ;



  procedure WRITE(L : inout line; VALUE : in ptcalc_rt) is

    variable v_slc_muid_r : SLC_MUID_rt;
    variable v_eta        : std_logic_vector(PTCALC_ETA_LEN-1 downto 0);
    variable v_pt         : std_logic_vector(PTCALC_PT_LEN-1 downto 0);
    variable v_ptthresh   : std_logic_vector(PTCALC_PTTHRESH_LEN-1 downto 0);
    variable v_charge     : std_logic;
    variable v_nsegments  : std_logic_vector(PTCALC_NSEGMENTS_LEN-1 downto 0);
    variable v_quality    : std_logic_vector(PTCALC_QUALITY_LEN-1 downto 0);

  begin

    v_slc_muid_r := VALUE.slc_muid_r;
    v_eta        := VALUE.eta;
    v_pt         := VALUE.pt;
    v_ptthresh   := VALUE.ptthresh;
    v_charge     := VALUE.charge;
    v_nsegments  := VALUE.nsegments;
    v_quality    := VALUE.quality;
    WRITE(L, v_slc_muid_r);
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_eta)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_pt)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_ptthresh)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned'("" & v_charge)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_nsegments)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_quality)));
  end WRITE;


  procedure READ(L : inout line; VALUE : out slcpipe_mtc_endcap_rt) is
    variable i_busy   : integer;
    variable i_destsl : integer;

    variable v_slc_muid_r   : SLC_MUID_rt;
    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_busy         : std_logic;
    variable v_destsl       : std_logic_vector(SLCPIPE_MTC_ENDCAP_DESTSL_LEN-1 downto 0);

    variable v_SPACE : character;

  begin

    READ(L, v_slc_muid_r);
    READ(L, v_SPACE);
    READ(L, v_slc_common_r);
    READ(L, v_SPACE);
    READ(L, i_busy);
    READ(L, v_SPACE);
    READ(L, i_destsl);

    v_busy   := std_logic(to_unsigned(i_busy, 1)(0));
    v_destsl := std_logic_vector(to_unsigned(i_destsl, SLCPIPE_MTC_ENDCAP_DESTSL_LEN));
    VALUE := (
      slc_muid_r   => v_slc_muid_r,
      slc_common_r => v_slc_common_r,
      busy         => v_busy,
      destsl       => v_destsl);
  end READ;



  procedure WRITE(L : inout line; VALUE : in slcpipe_mtc_endcap_rt) is

    variable v_slc_muid_r   : SLC_MUID_rt;
    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_busy         : std_logic;
    variable v_destsl       : std_logic_vector(SLCPIPE_MTC_ENDCAP_DESTSL_LEN-1 downto 0);

  begin

    v_slc_muid_r   := VALUE.slc_muid_r;
    v_slc_common_r := VALUE.slc_common_r;
    v_busy         := VALUE.busy;
    v_destsl       := VALUE.destsl;
    WRITE(L, v_slc_muid_r);
    WRITE(L, ' ');
    WRITE(L, v_slc_common_r);
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned'("" & v_busy)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_destsl)));
  end WRITE;


  procedure READ(L : inout line; VALUE : out slcpipe_mtc_barrel_rt) is
    variable i_cointype : integer;
    variable i_busy     : integer;
    variable i_destsl   : integer;

    variable v_cointype     : std_logic_vector(SLCPIPE_MTC_BARREL_COINTYPE_LEN-1 downto 0);
    variable v_slc_muid_r   : SLC_MUID_rt;
    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_busy         : std_logic;
    variable v_destsl       : std_logic_vector(SLCPIPE_MTC_BARREL_DESTSL_LEN-1 downto 0);

    variable v_SPACE : character;

  begin

    READ(L, i_cointype);
    READ(L, v_SPACE);
    READ(L, v_slc_muid_r);
    READ(L, v_SPACE);
    READ(L, v_slc_common_r);
    READ(L, v_SPACE);
    READ(L, i_busy);
    READ(L, v_SPACE);
    READ(L, i_destsl);

    v_cointype := std_logic_vector(to_unsigned(i_cointype, SLCPIPE_MTC_BARREL_COINTYPE_LEN));
    v_busy     := std_logic(to_unsigned(i_busy, 1)(0));
    v_destsl   := std_logic_vector(to_unsigned(i_destsl, SLCPIPE_MTC_BARREL_DESTSL_LEN));
    VALUE := (
      cointype     => v_cointype,
      slc_muid_r   => v_slc_muid_r,
      slc_common_r => v_slc_common_r,
      busy         => v_busy,
      destsl       => v_destsl);
  end READ;



  procedure WRITE(L : inout line; VALUE : in slcpipe_mtc_barrel_rt) is

    variable v_cointype     : std_logic_vector(SLCPIPE_MTC_BARREL_COINTYPE_LEN-1 downto 0);
    variable v_slc_muid_r   : SLC_MUID_rt;
    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_busy         : std_logic;
    variable v_destsl       : std_logic_vector(SLCPIPE_MTC_BARREL_DESTSL_LEN-1 downto 0);

  begin

    v_cointype     := VALUE.cointype;
    v_slc_muid_r   := VALUE.slc_muid_r;
    v_slc_common_r := VALUE.slc_common_r;
    v_busy         := VALUE.busy;
    v_destsl       := VALUE.destsl;
    WRITE(L, to_integer(unsigned(v_cointype)));
    WRITE(L, ' ');
    WRITE(L, v_slc_muid_r);
    WRITE(L, ' ');
    WRITE(L, v_slc_common_r);
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned'("" & v_busy)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_destsl)));
  end WRITE;


  procedure READ(L : inout line; VALUE : out mtc_rt) is
    variable i_eta       : integer;
    variable i_pt        : integer;
    variable i_ptthresh  : integer;
    variable i_charge    : integer;
    variable i_procflags : integer;
    variable i_nsegments : integer;
    variable i_quality   : integer;

    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_eta          : std_logic_vector(MTC_ETA_LEN-1 downto 0);
    variable v_pt           : std_logic_vector(MTC_PT_LEN-1 downto 0);
    variable v_ptthresh     : std_logic_vector(MTC_PTTHRESH_LEN-1 downto 0);
    variable v_charge       : std_logic;
    variable v_procflags    : std_logic_vector(MTC_PROCFLAGS_LEN-1 downto 0);
    variable v_nsegments    : std_logic_vector(MTC_NSEGMENTS_LEN-1 downto 0);
    variable v_quality      : std_logic_vector(MTC_QUALITY_LEN-1 downto 0);

    variable v_SPACE : character;

  begin

    READ(L, v_slc_common_r);
    READ(L, v_SPACE);
    READ(L, i_eta);
    READ(L, v_SPACE);
    READ(L, i_pt);
    READ(L, v_SPACE);
    READ(L, i_ptthresh);
    READ(L, v_SPACE);
    READ(L, i_charge);
    READ(L, v_SPACE);
    READ(L, i_procflags);
    READ(L, v_SPACE);
    READ(L, i_nsegments);
    READ(L, v_SPACE);
    READ(L, i_quality);

    v_eta       := std_logic_vector(to_unsigned(i_eta, MTC_ETA_LEN));
    v_pt        := std_logic_vector(to_unsigned(i_pt, MTC_PT_LEN));
    v_ptthresh  := std_logic_vector(to_unsigned(i_ptthresh, MTC_PTTHRESH_LEN));
    v_charge    := std_logic(to_unsigned(i_charge, 1)(0));
    v_procflags := std_logic_vector(to_unsigned(i_procflags, MTC_PROCFLAGS_LEN));
    v_nsegments := std_logic_vector(to_unsigned(i_nsegments, MTC_NSEGMENTS_LEN));
    v_quality   := std_logic_vector(to_unsigned(i_quality, MTC_QUALITY_LEN));
    VALUE := (
      slc_common_r => v_slc_common_r,
      eta          => v_eta,
      pt           => v_pt,
      ptthresh     => v_ptthresh,
      charge       => v_charge,
      procflags    => v_procflags,
      nsegments    => v_nsegments,
      quality      => v_quality);
  end READ;



  procedure WRITE(L : inout line; VALUE : in mtc_rt) is

    variable v_slc_common_r : SLC_COMMON_rt;
    variable v_eta          : std_logic_vector(MTC_ETA_LEN-1 downto 0);
    variable v_pt           : std_logic_vector(MTC_PT_LEN-1 downto 0);
    variable v_ptthresh     : std_logic_vector(MTC_PTTHRESH_LEN-1 downto 0);
    variable v_charge       : std_logic;
    variable v_procflags    : std_logic_vector(MTC_PROCFLAGS_LEN-1 downto 0);
    variable v_nsegments    : std_logic_vector(MTC_NSEGMENTS_LEN-1 downto 0);
    variable v_quality      : std_logic_vector(MTC_QUALITY_LEN-1 downto 0);

  begin

    v_slc_common_r := VALUE.slc_common_r;
    v_eta          := VALUE.eta;
    v_pt           := VALUE.pt;
    v_ptthresh     := VALUE.ptthresh;
    v_charge       := VALUE.charge;
    v_procflags    := VALUE.procflags;
    v_nsegments    := VALUE.nsegments;
    v_quality      := VALUE.quality;
    WRITE(L, v_slc_common_r);
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_eta)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_pt)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_ptthresh)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned'("" & v_charge)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_procflags)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_nsegments)));
    WRITE(L, ' ');
    WRITE(L, to_integer(unsigned(v_quality)));
  end WRITE;

end mdttp_textio;
