
----------------------------------------------------------------------
-- Automatically generated by 'make_textio.pl' from /home/hazen/work/l0mdt-hdl-design/shared/types/common_types_pkg.vhd
----------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.std_logic_textio.all;
use std.textio.all;

library l0mdt_lib;
use l0mdt_lib.mdttp_constants_pkg.all;
use l0mdt_lib.mdttp_types_pkg.all;

package mdttp_textio is


  procedure READ(L:inout LINE; VALUE:out l0mdt_control_rt);
  procedure WRITE(L:inout LINE; VALUE:in l0mdt_control_rt);
	
  procedure READ(L:inout LINE; VALUE:out l0mdt_ttc_rt);
  procedure WRITE(L:inout LINE; VALUE:in l0mdt_ttc_rt);
	
  procedure READ(L:inout LINE; VALUE:out slc_rx_data_at);
  procedure WRITE(L:inout LINE; VALUE:in slc_rx_data_at);
	
  procedure READ(L:inout LINE; VALUE:out slc_rx_data_avt);
  procedure WRITE(L:inout LINE; VALUE:in slc_rx_data_avt);
	
  procedure READ(L:inout LINE; VALUE:out mdt_polmux_at);
  procedure WRITE(L:inout LINE; VALUE:in mdt_polmux_at);
	
  procedure READ(L:inout LINE; VALUE:out mdt_polmux_avt);
  procedure WRITE(L:inout LINE; VALUE:in mdt_polmux_avt);
	
  procedure READ(L:inout LINE; VALUE:out tar2hps_at);
  procedure WRITE(L:inout LINE; VALUE:in tar2hps_at);
	
  procedure READ(L:inout LINE; VALUE:out tar2hps_avt);
  procedure WRITE(L:inout LINE; VALUE:in tar2hps_avt);
	
  procedure READ(L:inout LINE; VALUE:out ucm_csf_barrel_rt);
  procedure WRITE(L:inout LINE; VALUE:in ucm_csf_barrel_rt);
	
  procedure READ(L:inout LINE; VALUE:out ucm_csf_endcap_rt);
  procedure WRITE(L:inout LINE; VALUE:in ucm_csf_endcap_rt);
	
  procedure READ(L:inout LINE; VALUE:out ucm2hps_rt);
  procedure WRITE(L:inout LINE; VALUE:in ucm2hps_rt);
	
  procedure READ(L:inout LINE; VALUE:out ucm2hps_at);
  procedure WRITE(L:inout LINE; VALUE:in ucm2hps_at);
	
  procedure READ(L:inout LINE; VALUE:out ucm2hps_avt);
  procedure WRITE(L:inout LINE; VALUE:in ucm2hps_avt);
	
  procedure READ(L:inout LINE; VALUE:out hp_hit_data_rt);
  procedure WRITE(L:inout LINE; VALUE:in hp_hit_data_rt);
	
  procedure READ(L:inout LINE; VALUE:out hp_hit_data_a_at);
  procedure WRITE(L:inout LINE; VALUE:in hp_hit_data_a_at);
	
  procedure READ(L:inout LINE; VALUE:out hp_hit_data_a_avt);
  procedure WRITE(L:inout LINE; VALUE:in hp_hit_data_a_avt);
	
  procedure READ(L:inout LINE; VALUE:out sf2pt_at);
  procedure WRITE(L:inout LINE; VALUE:in sf2pt_at);
	
  procedure READ(L:inout LINE; VALUE:out sf2pt_avt);
  procedure WRITE(L:inout LINE; VALUE:in sf2pt_avt);
	
  procedure READ(L:inout LINE; VALUE:out ucm2pl_at);
  procedure WRITE(L:inout LINE; VALUE:in ucm2pl_at);
	
  procedure READ(L:inout LINE; VALUE:out ucm2pl_avt);
  procedure WRITE(L:inout LINE; VALUE:in ucm2pl_avt);
	
  procedure READ(L:inout LINE; VALUE:out pl2pt_at);
  procedure WRITE(L:inout LINE; VALUE:in pl2pt_at);
	
  procedure READ(L:inout LINE; VALUE:out pl2pt_avt);
  procedure WRITE(L:inout LINE; VALUE:in pl2pt_avt);
	
  procedure READ(L:inout LINE; VALUE:out pl2mtc_at);
  procedure WRITE(L:inout LINE; VALUE:in pl2mtc_at);
	
  procedure READ(L:inout LINE; VALUE:out pl2mtc_avt);
  procedure WRITE(L:inout LINE; VALUE:in pl2mtc_avt);
	
  procedure READ(L:inout LINE; VALUE:out tf2mtc_at);
  procedure WRITE(L:inout LINE; VALUE:in tf2mtc_at);
	
  procedure READ(L:inout LINE; VALUE:out tf2mtc_avt);
  procedure WRITE(L:inout LINE; VALUE:in tf2mtc_avt);
	
  procedure READ(L:inout LINE; VALUE:out mtc_out_at);
  procedure WRITE(L:inout LINE; VALUE:in mtc_out_at);
	
  procedure READ(L:inout LINE; VALUE:out mtc_out_avt);
  procedure WRITE(L:inout LINE; VALUE:in mtc_out_avt);
	
  procedure READ(L:inout LINE; VALUE:out mtc2nsp_at);
  procedure WRITE(L:inout LINE; VALUE:in mtc2nsp_at);
	
  procedure READ(L:inout LINE; VALUE:out mtc2nsp_avt);
  procedure WRITE(L:inout LINE; VALUE:in mtc2nsp_avt);
	
  procedure READ(L:inout LINE; VALUE:out felix_stream_rt);
  procedure WRITE(L:inout LINE; VALUE:in felix_stream_rt);
	
  procedure READ(L:inout LINE; VALUE:out felix_stream_at);
  procedure WRITE(L:inout LINE; VALUE:in felix_stream_at);
	
  procedure READ(L:inout LINE; VALUE:out felix_stream_avt);
  procedure WRITE(L:inout LINE; VALUE:in felix_stream_avt);
	
end mdttp_textio;

package body mdttp_textio is

  -- round up vector length to multiple of 4
  function len4r(len : integer) return integer is
  begin
    return len + (3-((len-1) mod 4));
  end len4r;


  procedure READ(L:inout LINE; VALUE:out l0mdt_control_rt) is



  begin


    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in l0mdt_control_rt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out l0mdt_ttc_rt) is



  begin


    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in l0mdt_ttc_rt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out slc_rx_data_at) is

    variable v_index : integer;
    variable v_data : slc_rx_data_at;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in slc_rx_data_at) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out slc_rx_data_avt) is

    variable v_index : integer;
    variable v_data : slc_rx_data_avt;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in slc_rx_data_avt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out mdt_polmux_at) is

    variable v_index : integer;
    variable v_data : mdt_polmux_at;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in mdt_polmux_at) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out mdt_polmux_avt) is

    variable v_index : integer;
    variable v_data : mdt_polmux_avt;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in mdt_polmux_avt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out tar2hps_at) is

    variable v_index : integer;
    variable v_data : tar2hps_at;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in tar2hps_at) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out tar2hps_avt) is

    variable v_index : integer;
    variable v_data : tar2hps_avt;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in tar2hps_avt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out ucm_csf_barrel_rt) is



  begin


    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in ucm_csf_barrel_rt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out ucm_csf_endcap_rt) is



  begin


    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in ucm_csf_endcap_rt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out ucm2hps_rt) is



  begin


    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in ucm2hps_rt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out ucm2hps_at) is

    variable v_index : integer;
    variable v_data : ucm2hps_at;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in ucm2hps_at) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out ucm2hps_avt) is

    variable v_index : integer;
    variable v_data : ucm2hps_avt;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in ucm2hps_avt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out hp_hit_data_rt) is



  begin


    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in hp_hit_data_rt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out hp_hit_data_a_at) is

    variable v_index : integer;
    variable v_data : hp_hit_data_a_at;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in hp_hit_data_a_at) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out hp_hit_data_a_avt) is

    variable v_index : integer;
    variable v_data : hp_hit_data_a_avt;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in hp_hit_data_a_avt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out sf2pt_at) is

    variable v_index : integer;
    variable v_data : sf2pt_at;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in sf2pt_at) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out sf2pt_avt) is

    variable v_index : integer;
    variable v_data : sf2pt_avt;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in sf2pt_avt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out ucm2pl_at) is

    variable v_index : integer;
    variable v_data : ucm2pl_at;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in ucm2pl_at) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out ucm2pl_avt) is

    variable v_index : integer;
    variable v_data : ucm2pl_avt;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in ucm2pl_avt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out pl2pt_at) is

    variable v_index : integer;
    variable v_data : pl2pt_at;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in pl2pt_at) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out pl2pt_avt) is

    variable v_index : integer;
    variable v_data : pl2pt_avt;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in pl2pt_avt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out pl2mtc_at) is

    variable v_index : integer;
    variable v_data : pl2mtc_at;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in pl2mtc_at) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out pl2mtc_avt) is

    variable v_index : integer;
    variable v_data : pl2mtc_avt;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in pl2mtc_avt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out tf2mtc_at) is

    variable v_index : integer;
    variable v_data : tf2mtc_at;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in tf2mtc_at) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out tf2mtc_avt) is

    variable v_index : integer;
    variable v_data : tf2mtc_avt;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in tf2mtc_avt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out mtc_out_at) is

    variable v_index : integer;
    variable v_data : mtc_out_at;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in mtc_out_at) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out mtc_out_avt) is

    variable v_index : integer;
    variable v_data : mtc_out_avt;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in mtc_out_avt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out mtc2nsp_at) is

    variable v_index : integer;
    variable v_data : mtc2nsp_at;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in mtc2nsp_at) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out mtc2nsp_avt) is

    variable v_index : integer;
    variable v_data : mtc2nsp_avt;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in mtc2nsp_avt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out felix_stream_rt) is



  begin


    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in felix_stream_rt) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out felix_stream_at) is

    variable v_index : integer;
    variable v_data : felix_stream_at;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in felix_stream_at) is


    variable v_SPACE : character;

  begin

  end WRITE;


  procedure READ(L:inout LINE; VALUE:out felix_stream_avt) is

    variable v_index : integer;
    variable v_data : felix_stream_avt;


  begin

    READ(L, v_index);
    READ(L, v_data(v_index));

    VALUE := (
  end READ;



  procedure WRITE(L:inout LINE; VALUE:in felix_stream_avt) is


    variable v_SPACE : character;

  begin

  end WRITE;

end mdttp_textio;
